In [1]:
import numpy as np
from scipy import io
from scipy.stats import linregress, describe

In [2]:
subplots_data = io.loadmat('subplots.mat')
subplots = subplots_data['subplots']
np.shape(subplots)

(584, 60)

In [3]:
lai_data = io.loadmat('fieldlai.mat')
lai = lai_data['fieldlai']

In [4]:
lai

array([[2.54, 2.88, 2.13, 1.58, 1.94, 2.69, 3.6 , 5.11, 2.06, 5.09, 3.72,
        3.45, 3.3 , 2.76, 5.54, 6.16, 5.26, 4.47, 2.82, 1.63, 2.42, 2.33,
        2.84, 2.12, 1.65, 2.82, 1.64, 1.95, 2.46, 1.62, 2.02, 1.76, 1.31,
        2.25, 2.23, 4.94, 2.96, 3.33, 4.15, 4.13, 3.12, 2.76, 3.53, 3.09,
        5.43, 5.29, 4.39, 4.24, 2.74, 1.98, 3.05, 3.02, 1.96, 1.09, 1.43,
        2.2 , 1.4 , 1.08, 1.38, 1.36]])

In [5]:
np.shape(subplots)

(584, 60)

In [6]:
subplots[0]

array([1.63317647, 1.38608824, 1.62261765, 1.79544118, 1.68752941,
       1.67151471, 1.47005882, 1.59147059, 1.82079412, 1.59147059,
       1.57344118, 1.50098529, 1.68394118, 1.57008824, 1.08202941,
       1.20861765, 1.25638235, 1.08070588, 1.57085294, 2.16738235,
       1.95238235, 1.81352941, 2.08175   , 1.90726471, 2.09808824,
       2.08175   , 2.33644118, 2.22614706, 2.57552941, 2.33644118,
       1.86614706, 2.0985    , 2.11570588, 1.97244118, 1.97244118,
       1.40517647, 1.28297059, 1.16147059, 1.22147059, 1.22147059,
       1.31923529, 1.57044118, 1.5285    , 1.31923529, 1.80142647,
       1.80820588, 2.04101471, 1.59355882, 1.36820588, 1.83016176,
       1.79188235, 1.79188235, 1.83016176, 2.00617647, 1.58475   ,
       1.91720588, 1.58475   , 2.21720588, 2.12017647, 1.88023529])

In [7]:
#NDVI=(infrared - red)/(infrared + red)
nir = subplots[298]
red = subplots[194]

NDVIs = (nir - red)/(nir + red)

In [8]:
NDVIs

array([0.80124622, 0.81770987, 0.76473776, 0.72382544, 0.64873222,
       0.75548466, 0.89082889, 0.89531476, 0.7884871 , 0.89531476,
       0.81173747, 0.80333766, 0.77236223, 0.80382923, 0.85751949,
       0.8580105 , 0.87559191, 0.86222756, 0.80474732, 0.57425708,
       0.66968322, 0.78267067, 0.75507011, 0.76554682, 0.68010971,
       0.75507011, 0.67566579, 0.71202606, 0.62519671, 0.67566579,
       0.67060712, 0.60581282, 0.64227121, 0.64010997, 0.64010997,
       0.86753392, 0.84236327, 0.85384694, 0.85905979, 0.85905979,
       0.78285882, 0.7369968 , 0.79290395, 0.78285882, 0.84722039,
       0.84686323, 0.74473159, 0.83565894, 0.853673  , 0.78758038,
       0.85288855, 0.85288855, 0.78758038, 0.75434658, 0.82933658,
       0.74444646, 0.82933658, 0.75425191, 0.75075183, 0.82470582])

In [9]:
coeff = linregress(NDVIs, lai) # calculate linear regression

In [10]:
coeff.rvalue**2 #square the r_value to get coefficient of determination

0.4111413434942934

In [ ]:
NDVIn = np.empty([1,3])
for i,j in [(i, j) for i in enumerate(subplots) for j in enumerate(subplots)]:
    NDVI = (i[1]-j[1])/(i[1]+j[1])
    coeff = linregress(NDVI, lai)
    coeff = (coeff.rvalue**2, i[0], j[0])
    coeff = np.array(coeff)
    print(coeff)
    NDVIn = np.vstack((NDVIn, coeff))

C:\Users\dwhew\anaconda3\envs\geo_env\lib\site-packages\scipy\stats\_stats_mstats_common.py:160: RuntimeWarning: invalid value encountered in double_scalars
  slope = ssxym / ssxm
C:\Users\dwhew\anaconda3\envs\geo_env\lib\site-packages\scipy\stats\_stats_mstats_common.py:176: RuntimeWarning: divide by zero encountered in double_scalars
  slope_stderr = np.sqrt((1 - r**2) * ssym / ssxm / df)
C:\Users\dwhew\anaconda3\envs\geo_env\lib\site-packages\scipy\stats\_stats_mstats_common.py:183: RuntimeWarning: invalid value encountered in double_scalars
  intercept_stderr = slope_stderr * np.sqrt(ssxm + xmean**2)


[0. 0. 0.]
[0.08115482 0.         1.        ]
[0.08257191 0.         2.        ]
[0.0836525 0.        3.       ]
[0.08432456 0.         4.        ]
[0.08451635 0.         5.        ]
[0.08416149 0.         6.        ]
[0.08320508 0.         7.        ]
[0.08098395 0.         8.        ]
[0.07566042 0.         9.        ]
[ 0.07067371  0.         10.        ]
[ 0.06958475  0.         11.        ]
[ 0.06982453  0.         12.        ]
[ 0.06697719  0.         13.        ]
[ 0.05904813  0.         14.        ]
[ 0.05345866  0.         15.        ]
[ 0.04675817  0.         16.        ]
[ 0.04017944  0.         17.        ]
[ 0.03564674  0.         18.        ]
[ 0.03523162  0.         19.        ]
[ 0.03313787  0.         20.        ]
[ 0.03275662  0.         21.        ]
[ 0.03530226  0.         22.        ]
[ 0.03982467  0.         23.        ]
[ 0.0428842  0.        24.       ]
[ 0.04741685  0.         25.        ]
[ 0.05411891  0.         26.        ]
[ 0.06010328  0.         27.      

[  0.46435676   0.         234.        ]
[  0.46692297   0.         235.        ]
[  0.46906233   0.         236.        ]
[  0.47086312   0.         237.        ]
[  0.47237558   0.         238.        ]
[  0.473574   0.       239.      ]
[  0.47455711   0.         240.        ]
[  0.47523364   0.         241.        ]
[  0.4756602   0.        242.       ]
[  0.47600696   0.         243.        ]
[  0.47677895   0.         244.        ]
[  0.47787316   0.         245.        ]
[  0.47922812   0.         246.        ]
[  0.48067446   0.         247.        ]
[  0.48173087   0.         248.        ]
[  0.4825973   0.        249.       ]
[  0.48308871   0.         250.        ]
[  0.48333627   0.         251.        ]
[  0.48333884   0.         252.        ]
[  0.4830425   0.        253.       ]
[  0.48246537   0.         254.        ]
[  0.4816268   0.        255.       ]
[  0.48074378   0.         256.        ]
[  0.48016828   0.         257.        ]
[  0.48025577   0.         258.   

[  0.48060333   0.         442.        ]
[  0.47576302   0.         443.        ]
[  0.47947589   0.         444.        ]
[  0.48438182   0.         445.        ]
[  0.49220229   0.         446.        ]
[  0.50609593   0.         447.        ]
[  0.52147719   0.         448.        ]
[  0.53185857   0.         449.        ]
[  0.53409092   0.         450.        ]
[  0.5221792   0.        451.       ]
[  0.49679148   0.         452.        ]
[  0.45756569   0.         453.        ]
[4.05300648e-01 0.00000000e+00 4.54000000e+02]
[3.48274017e-01 0.00000000e+00 4.55000000e+02]
[2.78519812e-01 0.00000000e+00 4.56000000e+02]
[2.03523534e-01 0.00000000e+00 4.57000000e+02]
[1.31861135e-01 0.00000000e+00 4.58000000e+02]
[7.79384917e-02 0.00000000e+00 4.59000000e+02]
[3.34431787e-02 0.00000000e+00 4.60000000e+02]
[1.44347139e-02 0.00000000e+00 4.61000000e+02]
[9.48205524e-03 0.00000000e+00 4.62000000e+02]
[9.03442902e-03 0.00000000e+00 4.63000000e+02]
[1.3165097e-02 0.0000000e+00 4.6400000e+0

[4.58696612e-03 1.00000000e+00 8.00000000e+01]
[1.38730048e-02 1.00000000e+00 8.10000000e+01]
[2.69310925e-02 1.00000000e+00 8.20000000e+01]
[4.34437842e-02 1.00000000e+00 8.30000000e+01]
[6.17506868e-02 1.00000000e+00 8.40000000e+01]
[8.07383208e-02 1.00000000e+00 8.50000000e+01]
[ 0.0990897  1.        86.       ]
[ 0.1160974  1.        87.       ]
[ 0.13123121  1.         88.        ]
[ 0.14452084  1.         89.        ]
[ 0.15594873  1.         90.        ]
[ 0.16519077  1.         91.        ]
[ 0.17252555  1.         92.        ]
[ 0.17813228  1.         93.        ]
[ 0.1821357  1.        94.       ]
[ 0.18430992  1.         95.        ]
[ 0.18510516  1.         96.        ]
[ 0.18505727  1.         97.        ]
[ 0.18400176  1.         98.        ]
[ 0.18261109  1.         99.        ]
[  0.18050955   1.         100.        ]
[  0.17817394   1.         101.        ]
[  0.17602507   1.         102.        ]
[  0.17364149   1.         103.        ]
[  0.17154663   1.         104.

[  0.49541246   1.         298.        ]
[  0.49572941   1.         299.        ]
[  0.49594941   1.         300.        ]
[  0.49615806   1.         301.        ]
[  0.49630292   1.         302.        ]
[  0.49652381   1.         303.        ]
[  0.49684659   1.         304.        ]
[  0.49710599   1.         305.        ]
[  0.49738574   1.         306.        ]
[  0.49768658   1.         307.        ]
[  0.49801755   1.         308.        ]
[  0.49839814   1.         309.        ]
[  0.49880401   1.         310.        ]
[  0.4991378   1.        311.       ]
[  0.4994829   1.        312.       ]
[  0.49970843   1.         313.        ]
[  0.49982973   1.         314.        ]
[  0.50015008   1.         315.        ]
[  0.50044241   1.         316.        ]
[  0.50070975   1.         317.        ]
[  0.50108139   1.         318.        ]
[  0.50132934   1.         319.        ]
[  0.50165459   1.         320.        ]
[  0.50196358   1.         321.        ]
[  0.50219725   1.    

[2.22908772e-01 1.00000000e+00 5.11000000e+02]
[2.04020081e-01 1.00000000e+00 5.12000000e+02]
[1.87959136e-01 1.00000000e+00 5.13000000e+02]
[1.68957722e-01 1.00000000e+00 5.14000000e+02]
[1.52765147e-01 1.00000000e+00 5.15000000e+02]
[1.33742644e-01 1.00000000e+00 5.16000000e+02]
[1.15826533e-01 1.00000000e+00 5.17000000e+02]
[9.83806228e-02 1.00000000e+00 5.18000000e+02]
[8.12956034e-02 1.00000000e+00 5.19000000e+02]
[6.75589411e-02 1.00000000e+00 5.20000000e+02]
[5.46002357e-02 1.00000000e+00 5.21000000e+02]
[4.28173927e-02 1.00000000e+00 5.22000000e+02]
[3.22115103e-02 1.00000000e+00 5.23000000e+02]
[2.28323362e-02 1.00000000e+00 5.24000000e+02]
[1.46025662e-02 1.00000000e+00 5.25000000e+02]
[8.51443941e-03 1.00000000e+00 5.26000000e+02]
[4.00156586e-03 1.00000000e+00 5.27000000e+02]
[9.93539243e-04 1.00000000e+00 5.28000000e+02]
[2.72237713e-05 1.00000000e+00 5.29000000e+02]
[2.41801744e-03 1.00000000e+00 5.30000000e+02]
[1.04528242e-02 1.00000000e+00 5.31000000e+02]
[2.75827544e-

[2.72502385e-02 2.00000000e+00 1.62000000e+02]
[2.87717857e-02 2.00000000e+00 1.63000000e+02]
[3.06483255e-02 2.00000000e+00 1.64000000e+02]
[3.29158619e-02 2.00000000e+00 1.65000000e+02]
[3.54452816e-02 2.00000000e+00 1.66000000e+02]
[3.83726932e-02 2.00000000e+00 1.67000000e+02]
[4.15463132e-02 2.00000000e+00 1.68000000e+02]
[4.52556471e-02 2.00000000e+00 1.69000000e+02]
[4.89082634e-02 2.00000000e+00 1.70000000e+02]
[5.2466199e-02 2.0000000e+00 1.7100000e+02]
[5.57637146e-02 2.00000000e+00 1.72000000e+02]
[5.89152598e-02 2.00000000e+00 1.73000000e+02]
[6.18924995e-02 2.00000000e+00 1.74000000e+02]
[6.47665848e-02 2.00000000e+00 1.75000000e+02]
[6.76666249e-02 2.00000000e+00 1.76000000e+02]
[7.05063961e-02 2.00000000e+00 1.77000000e+02]
[7.3374338e-02 2.0000000e+00 1.7800000e+02]
[7.63537237e-02 2.00000000e+00 1.79000000e+02]
[7.93383437e-02 2.00000000e+00 1.80000000e+02]
[8.24745302e-02 2.00000000e+00 1.81000000e+02]
[8.56238403e-02 2.00000000e+00 1.82000000e+02]
[8.89069441e-02 2.0

[  0.50355894   2.         379.        ]
[  0.50317331   2.         380.        ]
[  0.50337282   2.         381.        ]
[  0.50364677   2.         382.        ]
[  0.50423944   2.         383.        ]
[  0.50490448   2.         384.        ]
[  0.50589909   2.         385.        ]
[  0.50698196   2.         386.        ]
[  0.50745295   2.         387.        ]
[  0.50785535   2.         388.        ]
[  0.50840578   2.         389.        ]
[  0.50878784   2.         390.        ]
[  0.50891175   2.         391.        ]
[  0.50896501   2.         392.        ]
[  0.50914841   2.         393.        ]
[  0.50926839   2.         394.        ]
[  0.51017412   2.         395.        ]
[  0.51029191   2.         396.        ]
[  0.51113333   2.         397.        ]
[  0.51141721   2.         398.        ]
[  0.51173475   2.         399.        ]
[  0.51315133   2.         400.        ]
[  0.51421167   2.         401.        ]
[  0.51517577   2.         402.        ]
[  0.51565154   

[ 0.05324536  3.         12.        ]
[ 0.04933294  3.         13.        ]
[ 0.04010877  3.         14.        ]
[ 0.03411961  3.         15.        ]
[ 0.02759643  3.         16.        ]
[ 0.02185477  3.         17.        ]
[ 0.01817446  3.         18.        ]
[1.81659814e-02 3.00000000e+00 1.90000000e+01]
[1.67224843e-02 3.00000000e+00 2.00000000e+01]
[1.66835549e-02 3.00000000e+00 2.10000000e+01]
[1.90928162e-02 3.00000000e+00 2.20000000e+01]
[ 0.02331945  3.         23.        ]
[ 0.02631907  3.         24.        ]
[ 0.03063161  3.         25.        ]
[ 0.03703398  3.         26.        ]
[ 0.04279561  3.         27.        ]
[ 0.04853737  3.         28.        ]
[ 0.05430519  3.         29.        ]
[ 0.05909324  3.         30.        ]
[ 0.06232983  3.         31.        ]
[ 0.06459886  3.         32.        ]
[ 0.06682296  3.         33.        ]
[ 0.06898787  3.         34.        ]
[ 0.07008997  3.         35.        ]
[ 0.07328538  3.         36.        ]
[ 0.07502317  

[  0.46928946   3.         233.        ]
[  0.47195983   3.         234.        ]
[  0.47432142   3.         235.        ]
[  0.47627949   3.         236.        ]
[  0.47792133   3.         237.        ]
[  0.47929875   3.         238.        ]
[  0.48038091   3.         239.        ]
[  0.48126412   3.         240.        ]
[  0.48185571   3.         241.        ]
[  0.48221732   3.         242.        ]
[  0.48250813   3.         243.        ]
[  0.48322595   3.         244.        ]
[  0.48426127   3.         245.        ]
[  0.48555518   3.         246.        ]
[  0.48693888   3.         247.        ]
[  0.48794338   3.         248.        ]
[  0.48876905   3.         249.        ]
[  0.48923224   3.         250.        ]
[  0.48945761   3.         251.        ]
[  0.48944703   3.         252.        ]
[  0.48914473   3.         253.        ]
[  0.48857243   3.         254.        ]
[  0.48774719   3.         255.        ]
[  0.48688472   3.         256.        ]
[  0.48632072   

[1.48876089e-02 3.00000000e+00 4.62000000e+02]
[1.4513456e-02 3.0000000e+00 4.6300000e+02]
[1.99586209e-02 3.00000000e+00 4.64000000e+02]
[3.06333249e-02 3.00000000e+00 4.65000000e+02]
[4.72085782e-02 3.00000000e+00 4.66000000e+02]
[6.773053e-02 3.000000e+00 4.670000e+02]
[8.97840471e-02 3.00000000e+00 4.68000000e+02]
[1.17098436e-01 3.00000000e+00 4.69000000e+02]
[1.44155137e-01 3.00000000e+00 4.70000000e+02]
[1.68301571e-01 3.00000000e+00 4.71000000e+02]
[1.92583037e-01 3.00000000e+00 4.72000000e+02]
[2.11993287e-01 3.00000000e+00 4.73000000e+02]
[2.25535601e-01 3.00000000e+00 4.74000000e+02]
[2.35698435e-01 3.00000000e+00 4.75000000e+02]
[2.44010765e-01 3.00000000e+00 4.76000000e+02]
[2.51319116e-01 3.00000000e+00 4.77000000e+02]
[2.59261278e-01 3.00000000e+00 4.78000000e+02]
[2.70122294e-01 3.00000000e+00 4.79000000e+02]
[2.7871012e-01 3.0000000e+00 4.8000000e+02]
[2.86122267e-01 3.00000000e+00 4.81000000e+02]
[2.92899603e-01 3.00000000e+00 4.82000000e+02]
[2.9880103e-01 3.0000000e

[7.11931615e-03 4.00000000e+00 7.60000000e+01]
[1.8214727e-03 4.0000000e+00 7.7000000e+01]
[9.86442906e-06 4.00000000e+00 7.80000000e+01]
[2.78701394e-03 4.00000000e+00 7.90000000e+01]
[1.06272379e-02 4.00000000e+00 8.00000000e+01]
[2.3406927e-02 4.0000000e+00 8.1000000e+01]
[3.94608589e-02 4.00000000e+00 8.20000000e+01]
[5.85361083e-02 4.00000000e+00 8.30000000e+01]
[7.883642e-02 4.000000e+00 8.400000e+01]
[ 0.09930658  4.         85.        ]
[ 0.11868819  4.         86.        ]
[ 0.13635402  4.         87.        ]
[ 0.15188771  4.         88.        ]
[ 0.16541872  4.         89.        ]
[ 0.17695698  4.         90.        ]
[ 0.18623498  4.         91.        ]
[ 0.19353623  4.         92.        ]
[ 0.19905216  4.         93.        ]
[ 0.20291399  4.         94.        ]
[ 0.20492664  4.         95.        ]
[ 0.20555891  4.         96.        ]
[ 0.20534896  4.         97.        ]
[ 0.20414093  4.         98.        ]
[ 0.2025987  4.        99.       ]
[  0.20036033   4.    

[  0.50032132   4.         289.        ]
[  0.50053969   4.         290.        ]
[  0.50057639   4.         291.        ]
[  0.50069857   4.         292.        ]
[  0.50083898   4.         293.        ]
[  0.50105842   4.         294.        ]
[  0.50129651   4.         295.        ]
[  0.5016262   4.        296.       ]
[  0.50181958   4.         297.        ]
[  0.50201636   4.         298.        ]
[  0.50233091   4.         299.        ]
[  0.50254861   4.         300.        ]
[  0.50275716   4.         301.        ]
[  0.50290288   4.         302.        ]
[  0.50312259   4.         303.        ]
[  0.50344061   4.         304.        ]
[  0.50369452   4.         305.        ]
[  0.50397006   4.         306.        ]
[  0.50426723   4.         307.        ]
[  0.50459451   4.         308.        ]
[  0.50496621   4.         309.        ]
[  0.50536372   4.         310.        ]
[  0.50569042   4.         311.        ]
[  0.50602485   4.         312.        ]
[  0.50624641   4. 

[1.84885878e-01 4.00000000e+00 5.14000000e+02]
[1.66580127e-01 4.00000000e+00 5.15000000e+02]
[1.45579539e-01 4.00000000e+00 5.16000000e+02]
[1.25872699e-01 4.00000000e+00 5.17000000e+02]
[1.06947896e-01 4.00000000e+00 5.18000000e+02]
[8.86928073e-02 4.00000000e+00 5.19000000e+02]
[7.41766287e-02 4.00000000e+00 5.20000000e+02]
[6.04577899e-02 4.00000000e+00 5.21000000e+02]
[4.79783791e-02 4.00000000e+00 5.22000000e+02]
[3.6707482e-02 4.0000000e+00 5.2300000e+02]
[2.66673322e-02 4.00000000e+00 5.24000000e+02]
[1.77415319e-02 4.00000000e+00 5.25000000e+02]
[1.09783523e-02 4.00000000e+00 5.26000000e+02]
[5.76411436e-03 4.00000000e+00 5.27000000e+02]
[1.96885632e-03 4.00000000e+00 5.28000000e+02]
[6.15163431e-05 4.00000000e+00 5.29000000e+02]
[1.29056799e-03 4.00000000e+00 5.30000000e+02]
[7.90818331e-03 4.00000000e+00 5.31000000e+02]
[2.34561988e-02 4.00000000e+00 5.32000000e+02]
[4.8326188e-02 4.0000000e+00 5.3300000e+02]
[8.76860215e-02 4.00000000e+00 5.34000000e+02]
[1.38187514e-01 4.0

[2.31799465e-04 5.00000000e+00 1.39000000e+02]
[5.91921728e-05 5.00000000e+00 1.40000000e+02]
[4.64197105e-08 5.00000000e+00 1.41000000e+02]
[6.14027541e-05 5.00000000e+00 1.42000000e+02]
[2.66170306e-04 5.00000000e+00 1.43000000e+02]
[6.08488464e-04 5.00000000e+00 1.44000000e+02]
[1.15380982e-03 5.00000000e+00 1.45000000e+02]
[1.91121032e-03 5.00000000e+00 1.46000000e+02]
[2.92688261e-03 5.00000000e+00 1.47000000e+02]
[4.1361169e-03 5.0000000e+00 1.4800000e+02]
[5.50810567e-03 5.00000000e+00 1.49000000e+02]
[7.10523095e-03 5.00000000e+00 1.50000000e+02]
[8.83869604e-03 5.00000000e+00 1.51000000e+02]
[1.06092428e-02 5.00000000e+00 1.52000000e+02]
[1.23291617e-02 5.00000000e+00 1.53000000e+02]
[1.38665585e-02 5.00000000e+00 1.54000000e+02]
[1.52366818e-02 5.00000000e+00 1.55000000e+02]
[1.64548525e-02 5.00000000e+00 1.56000000e+02]
[1.74223866e-02 5.00000000e+00 1.57000000e+02]
[1.82346447e-02 5.00000000e+00 1.58000000e+02]
[1.91081671e-02 5.00000000e+00 1.59000000e+02]
[2.00053137e-02 

[  0.51645765   5.         358.        ]
[  0.51625697   5.         359.        ]
[  0.516121   5.       360.      ]
[  0.51588225   5.         361.        ]
[  0.51573841   5.         362.        ]
[  0.51565448   5.         363.        ]
[  0.51586012   5.         364.        ]
[  0.51571983   5.         365.        ]
[  0.51573399   5.         366.        ]
[  0.51550238   5.         367.        ]
[  0.51541661   5.         368.        ]
[  0.51506532   5.         369.        ]
[  0.51447228   5.         370.        ]
[  0.51429053   5.         371.        ]
[  0.51412636   5.         372.        ]
[  0.51366929   5.         373.        ]
[  0.51305934   5.         374.        ]
[  0.51244638   5.         375.        ]
[  0.5119527   5.        376.       ]
[  0.51177089   5.         377.        ]
[  0.51120094   5.         378.        ]
[  0.51087308   5.         379.        ]
[  0.51052056   5.         380.        ]
[  0.51075545   5.         381.        ]
[  0.511092   5.       38

[6.95224341e-02 5.00000000e+00 5.67000000e+02]
[8.31164603e-02 5.00000000e+00 5.68000000e+02]
[1.00788493e-01 5.00000000e+00 5.69000000e+02]
[1.08625569e-01 5.00000000e+00 5.70000000e+02]
[1.18712599e-01 5.00000000e+00 5.71000000e+02]
[1.28806405e-01 5.00000000e+00 5.72000000e+02]
[1.45693728e-01 5.00000000e+00 5.73000000e+02]
[1.52046609e-01 5.00000000e+00 5.74000000e+02]
[1.59273978e-01 5.00000000e+00 5.75000000e+02]
[1.54986536e-01 5.00000000e+00 5.76000000e+02]
[1.56001429e-01 5.00000000e+00 5.77000000e+02]
[1.57705986e-01 5.00000000e+00 5.78000000e+02]
[1.5995091e-01 5.0000000e+00 5.7900000e+02]
[1.62514601e-01 5.00000000e+00 5.80000000e+02]
[1.65126213e-01 5.00000000e+00 5.81000000e+02]
[1.675199e-01 5.000000e+00 5.820000e+02]
[1.69552616e-01 5.00000000e+00 5.83000000e+02]
[0.08416149 6.         0.        ]
[0.08320202 6.         1.        ]
[0.08144766 6.         2.        ]
[0.07886821 6.         3.        ]
[0.07547831 6.         4.        ]
[0.07134248 6.         5.        ]


[  0.36988641   6.         220.        ]
[  0.3863529   6.        221.       ]
[  0.40117378   6.         222.        ]
[  0.41415432   6.         223.        ]
[  0.42549526   6.         224.        ]
[  0.43517638   6.         225.        ]
[  0.44346581   6.         226.        ]
[  0.45063228   6.         227.        ]
[  0.45702964   6.         228.        ]
[  0.46283358   6.         229.        ]
[  0.46807768   6.         230.        ]
[  0.47264808   6.         231.        ]
[  0.47627228   6.         232.        ]
[  0.47924339   6.         233.        ]
[  0.48168295   6.         234.        ]
[  0.48384057   6.         235.        ]
[  0.48561557   6.         236.        ]
[  0.48709439   6.         237.        ]
[  0.48833032   6.         238.        ]
[  0.48928899   6.         239.        ]
[  0.49006572   6.         240.        ]
[  0.49056448   6.         241.        ]
[  0.49085479   6.         242.        ]
[  0.49108663   6.         243.        ]
[  0.49174834   6. 

[  0.50968753   6.         430.        ]
[  0.51007595   6.         431.        ]
[  0.51050006   6.         432.        ]
[  0.51178779   6.         433.        ]
[  0.51263088   6.         434.        ]
[  0.51291116   6.         435.        ]
[  0.51300588   6.         436.        ]
[  0.51228415   6.         437.        ]
[  0.51180665   6.         438.        ]
[  0.51047948   6.         439.        ]
[  0.5080763   6.        440.       ]
[  0.50343544   6.         441.        ]
[  0.50346956   6.         442.        ]
[  0.499691   6.       443.      ]
[  0.50441882   6.         444.        ]
[  0.51029113   6.         445.        ]
[  0.51881615   6.         446.        ]
[  0.5346284   6.        447.       ]
[  0.55168518   6.         448.        ]
[  0.56390252   6.         449.        ]
[  0.56761842   6.         450.        ]
[  0.55680545   6.         451.        ]
[  0.53174145   6.         452.        ]
[  0.49230358   6.         453.        ]
[4.39938082e-01 6.00000000e+

[ 0.10463528  7.         58.        ]
[ 0.10376093  7.         59.        ]
[ 0.1026989  7.        60.       ]
[ 0.10140738  7.         61.        ]
[ 0.09751498  7.         62.        ]
[ 0.09339858  7.         63.        ]
[ 0.08983221  7.         64.        ]
[ 0.08501155  7.         65.        ]
[ 0.07973418  7.         66.        ]
[ 0.07349913  7.         67.        ]
[6.73299922e-02 7.00000000e+00 6.80000000e+01]
[6.08135468e-02 7.00000000e+00 6.90000000e+01]
[5.25415392e-02 7.00000000e+00 7.00000000e+01]
[4.41478592e-02 7.00000000e+00 7.10000000e+01]
[3.54752501e-02 7.00000000e+00 7.20000000e+01]
[2.64894929e-02 7.00000000e+00 7.30000000e+01]
[1.77949025e-02 7.00000000e+00 7.40000000e+01]
[9.88439014e-03 7.00000000e+00 7.50000000e+01]
[3.47838791e-03 7.00000000e+00 7.60000000e+01]
[2.44704826e-04 7.00000000e+00 7.70000000e+01]
[1.00086433e-03 7.00000000e+00 7.80000000e+01]
[6.79663215e-03 7.00000000e+00 7.90000000e+01]
[1.77993399e-02 7.00000000e+00 8.00000000e+01]
[3.36812718e

[  0.50112925   7.         265.        ]
[  0.50158561   7.         266.        ]
[  0.50199989   7.         267.        ]
[  0.50240272   7.         268.        ]
[  0.50276204   7.         269.        ]
[  0.50309117   7.         270.        ]
[  0.50344251   7.         271.        ]
[  0.50377878   7.         272.        ]
[  0.5041151   7.        273.       ]
[  0.50439327   7.         274.        ]
[  0.50462562   7.         275.        ]
[  0.50494982   7.         276.        ]
[  0.50520664   7.         277.        ]
[  0.50548232   7.         278.        ]
[  0.50575653   7.         279.        ]
[  0.50616496   7.         280.        ]
[  0.50653574   7.         281.        ]
[  0.50701063   7.         282.        ]
[  0.5073685   7.        283.       ]
[  0.5076586   7.        284.       ]
[  0.50801421   7.         285.        ]
[  0.50833478   7.         286.        ]
[  0.50864206   7.         287.        ]
[  0.50881233   7.         288.        ]
[  0.50896858   7.       

[1.07420086e-01 7.00000000e+00 4.68000000e+02]
[1.37025387e-01 7.00000000e+00 4.69000000e+02]
[1.65787491e-01 7.00000000e+00 4.70000000e+02]
[1.91250062e-01 7.00000000e+00 4.71000000e+02]
[2.16645291e-01 7.00000000e+00 4.72000000e+02]
[2.36902253e-01 7.00000000e+00 4.73000000e+02]
[2.51016538e-01 7.00000000e+00 4.74000000e+02]
[2.61523227e-01 7.00000000e+00 4.75000000e+02]
[2.70088548e-01 7.00000000e+00 4.76000000e+02]
[2.77694113e-01 7.00000000e+00 4.77000000e+02]
[2.85765493e-01 7.00000000e+00 4.78000000e+02]
[2.96733472e-01 7.00000000e+00 4.79000000e+02]
[3.05378109e-01 7.00000000e+00 4.80000000e+02]
[3.12645188e-01 7.00000000e+00 4.81000000e+02]
[3.192896e-01 7.000000e+00 4.820000e+02]
[3.2504653e-01 7.0000000e+00 4.8300000e+02]
[3.29701162e-01 7.00000000e+00 4.84000000e+02]
[3.31934281e-01 7.00000000e+00 4.85000000e+02]
[3.36574336e-01 7.00000000e+00 4.86000000e+02]
[3.37713599e-01 7.00000000e+00 4.87000000e+02]
[3.37377555e-01 7.00000000e+00 4.88000000e+02]
[3.37691992e-01 7.0000

[  0.16796947   8.         113.        ]
[  0.15766391   8.         114.        ]
[  0.14642003   8.         115.        ]
[  0.13482343   8.         116.        ]
[  0.12256956   8.         117.        ]
[1.10359197e-01 8.00000000e+00 1.18000000e+02]
[9.78456913e-02 8.00000000e+00 1.19000000e+02]
[8.57845949e-02 8.00000000e+00 1.20000000e+02]
[7.41394074e-02 8.00000000e+00 1.21000000e+02]
[6.35297252e-02 8.00000000e+00 1.22000000e+02]
[5.36769761e-02 8.00000000e+00 1.23000000e+02]
[4.48594251e-02 8.00000000e+00 1.24000000e+02]
[3.70396639e-02 8.00000000e+00 1.25000000e+02]
[3.02957316e-02 8.00000000e+00 1.26000000e+02]
[2.46554102e-02 8.00000000e+00 1.27000000e+02]
[1.99881479e-02 8.00000000e+00 1.28000000e+02]
[1.60033577e-02 8.00000000e+00 1.29000000e+02]
[1.28640193e-02 8.00000000e+00 1.30000000e+02]
[1.02445569e-02 8.00000000e+00 1.31000000e+02]
[8.12993492e-03 8.00000000e+00 1.32000000e+02]
[6.41831239e-03 8.00000000e+00 1.33000000e+02]
[5.0560818e-03 8.0000000e+00 1.3400000e+02]

[  0.51686639   8.         308.        ]
[  0.51722801   8.         309.        ]
[  0.51761513   8.         310.        ]
[  0.51793303   8.         311.        ]
[  0.51825232   8.         312.        ]
[  0.51846598   8.         313.        ]
[  0.51858379   8.         314.        ]
[  0.51889295   8.         315.        ]
[  0.51917659   8.         316.        ]
[  0.51943766   8.         317.        ]
[  0.51979814   8.         318.        ]
[  0.52003902   8.         319.        ]
[  0.5203594   8.        320.       ]
[  0.52066953   8.         321.        ]
[  0.52088412   8.         322.        ]
[  0.52113519   8.         323.        ]
[  0.52147489   8.         324.        ]
[  0.52161897   8.         325.        ]
[  0.52182766   8.         326.        ]
[  0.52195704   8.         327.        ]
[  0.52216071   8.         328.        ]
[  0.52248314   8.         329.        ]
[  0.52276553   8.         330.        ]
[  0.52295834   8.         331.        ]
[  0.52321655   8. 

[3.30944186e-03 8.00000000e+00 5.28000000e+02]
[4.54772842e-04 8.00000000e+00 5.29000000e+02]
[4.88296115e-04 8.00000000e+00 5.30000000e+02]
[5.59826025e-03 8.00000000e+00 5.31000000e+02]
[1.93600381e-02 8.00000000e+00 5.32000000e+02]
[4.25588932e-02 8.00000000e+00 5.33000000e+02]
[8.03724403e-02 8.00000000e+00 5.34000000e+02]
[1.29878176e-01 8.00000000e+00 5.35000000e+02]
[1.79985944e-01 8.00000000e+00 5.36000000e+02]
[2.3251114e-01 8.0000000e+00 5.3700000e+02]
[2.80379324e-01 8.00000000e+00 5.38000000e+02]
[3.15577635e-01 8.00000000e+00 5.39000000e+02]
[3.27398777e-01 8.00000000e+00 5.40000000e+02]
[3.29246032e-01 8.00000000e+00 5.41000000e+02]
[3.28321222e-01 8.00000000e+00 5.42000000e+02]
[3.28200568e-01 8.00000000e+00 5.43000000e+02]
[3.2632279e-01 8.0000000e+00 5.4400000e+02]
[3.18435887e-01 8.00000000e+00 5.45000000e+02]
[3.0542353e-01 8.0000000e+00 5.4600000e+02]
[2.8573931e-01 8.0000000e+00 5.4700000e+02]
[2.60072253e-01 8.00000000e+00 5.48000000e+02]
[2.19237085e-01 8.0000000

[4.3935383e-02 9.0000000e+00 2.0000000e+02]
[3.32981637e-02 9.00000000e+00 2.01000000e+02]
[2.20299582e-02 9.00000000e+00 2.02000000e+02]
[1.13165878e-02 9.00000000e+00 2.03000000e+02]
[3.12932622e-03 9.00000000e+00 2.04000000e+02]
[8.55578246e-06 9.00000000e+00 2.05000000e+02]
[4.60333932e-03 9.00000000e+00 2.06000000e+02]
[1.87020633e-02 9.00000000e+00 2.07000000e+02]
[4.27060898e-02 9.00000000e+00 2.08000000e+02]
[7.40917604e-02 9.00000000e+00 2.09000000e+02]
[1.09510886e-01 9.00000000e+00 2.10000000e+02]
[1.45617211e-01 9.00000000e+00 2.11000000e+02]
[1.80606627e-01 9.00000000e+00 2.12000000e+02]
[  0.2133725   9.        213.       ]
[  0.2435387   9.        214.       ]
[  0.27234059   9.         215.        ]
[  0.30007369   9.         216.        ]
[  0.32637274   9.         217.        ]
[  0.34985033   9.         218.        ]
[  0.37046238   9.         219.        ]
[  0.3883776   9.        220.       ]
[  0.40439531   9.         221.        ]
[  0.41869857   9.         222. 

[  0.53776837   9.         407.        ]
[  0.53790248   9.         408.        ]
[  0.5377192   9.        409.       ]
[  0.5373052   9.        410.       ]
[  0.53743744   9.         411.        ]
[  0.53787179   9.         412.        ]
[  0.53874525   9.         413.        ]
[  0.54054509   9.         414.        ]
[  0.54128286   9.         415.        ]
[  0.54151264   9.         416.        ]
[  0.54094416   9.         417.        ]
[  0.54059361   9.         418.        ]
[  0.53946475   9.         419.        ]
[  0.53811321   9.         420.        ]
[  0.53582801   9.         421.        ]
[  0.53337972   9.         422.        ]
[  0.53002196   9.         423.        ]
[  0.52677048   9.         424.        ]
[  0.52379593   9.         425.        ]
[  0.52182896   9.         426.        ]
[  0.52100205   9.         427.        ]
[  0.52169293   9.         428.        ]
[  0.52220332   9.         429.        ]
[  0.52298133   9.         430.        ]
[  0.52329079   9.    

[ 0.09595455 10.         54.        ]
[ 0.09879946 10.         55.        ]
[ 0.0999876 10.        56.       ]
[ 0.10110709 10.         57.        ]
[ 0.10041263 10.         58.        ]
[ 0.0994638 10.        59.       ]
[ 0.09835858 10.         60.        ]
[ 0.09703928 10.         61.        ]
[ 0.09306727 10.         62.        ]
[ 0.08889411 10.         63.        ]
[ 0.08528273 10.         64.        ]
[ 0.08041652 10.         65.        ]
[ 0.07507457 10.         66.        ]
[ 0.06879742 10.         67.        ]
[6.26043173e-02 1.00000000e+01 6.80000000e+01]
[5.60713234e-02 1.00000000e+01 6.90000000e+01]
[4.78143476e-02 1.00000000e+01 7.00000000e+01]
[3.94932025e-02 1.00000000e+01 7.10000000e+01]
[3.09788371e-02 1.00000000e+01 7.20000000e+01]
[2.22841263e-02 1.00000000e+01 7.30000000e+01]
[1.40780266e-02 1.00000000e+01 7.40000000e+01]
[6.93192296e-03 1.00000000e+01 7.50000000e+01]
[1.69875724e-03 1.00000000e+01 7.60000000e+01]
[1.35665616e-05 1.00000000e+01 7.70000000e+01]
[2.7

[  0.52527745  10.         311.        ]
[  0.52558832  10.         312.        ]
[  0.52579632  10.         313.        ]
[  0.52591101  10.         314.        ]
[  0.52621582  10.         315.        ]
[  0.52649438  10.         316.        ]
[  0.52675275  10.         317.        ]
[  0.52711114  10.         318.        ]
[  0.52734917  10.         319.        ]
[  0.5276683  10.        320.       ]
[  0.52797891  10.         321.        ]
[  0.52818734  10.         322.        ]
[  0.52843559  10.         323.        ]
[  0.52877183  10.         324.        ]
[  0.52890896  10.         325.        ]
[  0.52911146  10.         326.        ]
[  0.5292392  10.        327.       ]
[  0.52944147  10.         328.        ]
[  0.52975665  10.         329.        ]
[  0.53003545  10.         330.        ]
[  0.53022561  10.         331.        ]
[  0.53048291  10.         332.        ]
[  0.5306694  10.        333.       ]
[  0.53088273  10.         334.        ]
[  0.53101702  10.       

[1.18124207e-01 1.00000000e+01 5.51000000e+02]
[7.634156e-02 1.000000e+01 5.520000e+02]
[4.14820299e-02 1.00000000e+01 5.53000000e+02]
[1.83521935e-02 1.00000000e+01 5.54000000e+02]
[9.20846427e-03 1.00000000e+01 5.55000000e+02]
[6.57262078e-03 1.00000000e+01 5.56000000e+02]
[5.17564553e-03 1.00000000e+01 5.57000000e+02]
[6.40409273e-03 1.00000000e+01 5.58000000e+02]
[8.26169134e-03 1.00000000e+01 5.59000000e+02]
[1.01098238e-02 1.00000000e+01 5.60000000e+02]
[1.45075101e-02 1.00000000e+01 5.61000000e+02]
[1.51364739e-02 1.00000000e+01 5.62000000e+02]
[1.45423475e-02 1.00000000e+01 5.63000000e+02]
[1.67701712e-02 1.00000000e+01 5.64000000e+02]
[2.86172738e-02 1.00000000e+01 5.65000000e+02]
[4.34140611e-02 1.00000000e+01 5.66000000e+02]
[5.93987216e-02 1.00000000e+01 5.67000000e+02]
[7.24280524e-02 1.00000000e+01 5.68000000e+02]
[8.97912777e-02 1.00000000e+01 5.69000000e+02]
[9.82653818e-02 1.00000000e+01 5.70000000e+02]
[1.08736389e-01 1.00000000e+01 5.71000000e+02]
[1.19833663e-01 1.0

[6.75124711e-02 1.10000000e+01 1.81000000e+02]
[7.05887866e-02 1.10000000e+01 1.82000000e+02]
[7.38065534e-02 1.10000000e+01 1.83000000e+02]
[7.65673913e-02 1.10000000e+01 1.84000000e+02]
[7.93195528e-02 1.10000000e+01 1.85000000e+02]
[8.14933763e-02 1.10000000e+01 1.86000000e+02]
[8.3447628e-02 1.1000000e+01 1.8700000e+02]
[8.50432901e-02 1.10000000e+01 1.88000000e+02]
[8.64320505e-02 1.10000000e+01 1.89000000e+02]
[8.74397742e-02 1.10000000e+01 1.90000000e+02]
[8.76933745e-02 1.10000000e+01 1.91000000e+02]
[8.71813892e-02 1.10000000e+01 1.92000000e+02]
[8.56427623e-02 1.10000000e+01 1.93000000e+02]
[8.25855659e-02 1.10000000e+01 1.94000000e+02]
[7.82567805e-02 1.10000000e+01 1.95000000e+02]
[7.28760753e-02 1.10000000e+01 1.96000000e+02]
[6.6961884e-02 1.1000000e+01 1.9700000e+02]
[5.98616611e-02 1.10000000e+01 1.98000000e+02]
[5.14525626e-02 1.10000000e+01 1.99000000e+02]
[4.18205436e-02 1.10000000e+01 2.00000000e+02]
[3.13454771e-02 1.10000000e+01 2.01000000e+02]
[2.03145267e-02 1.1

[2.94288638e-01 1.10000000e+01 4.77000000e+02]
[3.0278442e-01 1.1000000e+01 4.7800000e+02]
[3.14120044e-01 1.10000000e+01 4.79000000e+02]
[3.23133351e-01 1.10000000e+01 4.80000000e+02]
[3.30512411e-01 1.10000000e+01 4.81000000e+02]
[3.37294695e-01 1.10000000e+01 4.82000000e+02]
[3.43153922e-01 1.10000000e+01 4.83000000e+02]
[3.48037077e-01 1.10000000e+01 4.84000000e+02]
[3.50522491e-01 1.10000000e+01 4.85000000e+02]
[3.55497918e-01 1.10000000e+01 4.86000000e+02]
[3.57030412e-01 1.10000000e+01 4.87000000e+02]
[3.56887738e-01 1.10000000e+01 4.88000000e+02]
[3.5740817e-01 1.1000000e+01 4.8900000e+02]
[3.58042395e-01 1.10000000e+01 4.90000000e+02]
[3.60196719e-01 1.10000000e+01 4.91000000e+02]
[3.61982871e-01 1.10000000e+01 4.92000000e+02]
[3.65314442e-01 1.10000000e+01 4.93000000e+02]
[3.66265462e-01 1.10000000e+01 4.94000000e+02]
[3.66936233e-01 1.10000000e+01 4.95000000e+02]
[3.68074788e-01 1.10000000e+01 4.96000000e+02]
[3.71422461e-01 1.10000000e+01 4.97000000e+02]
[3.70272795e-01 1.1

[5.17998637e-02 1.20000000e+01 1.76000000e+02]
[5.44878469e-02 1.20000000e+01 1.77000000e+02]
[5.72255423e-02 1.20000000e+01 1.78000000e+02]
[6.00942639e-02 1.20000000e+01 1.79000000e+02]
[6.29829777e-02 1.20000000e+01 1.80000000e+02]
[6.60189814e-02 1.20000000e+01 1.81000000e+02]
[6.9077046e-02 1.2000000e+01 1.8200000e+02]
[7.22771028e-02 1.20000000e+01 1.83000000e+02]
[7.50234763e-02 1.20000000e+01 1.84000000e+02]
[7.77610897e-02 1.20000000e+01 1.85000000e+02]
[7.99220398e-02 1.20000000e+01 1.86000000e+02]
[8.18635672e-02 1.20000000e+01 1.87000000e+02]
[8.34474934e-02 1.20000000e+01 1.88000000e+02]
[8.48254877e-02 1.20000000e+01 1.89000000e+02]
[8.58256634e-02 1.20000000e+01 1.90000000e+02]
[8.60746166e-02 1.20000000e+01 1.91000000e+02]
[8.55635379e-02 1.20000000e+01 1.92000000e+02]
[8.40306329e-02 1.20000000e+01 1.93000000e+02]
[8.09867099e-02 1.20000000e+01 1.94000000e+02]
[7.66780019e-02 1.20000000e+01 1.95000000e+02]
[7.13258981e-02 1.20000000e+01 1.96000000e+02]
[6.54473841e-02 

[  0.59544736  12.         449.        ]
[  0.59798413  12.         450.        ]
[  0.58514087  12.         451.        ]
[  0.5570845  12.        452.       ]
[  0.51447901  12.         453.        ]
[  0.45940987  12.         454.        ]
[4.00306439e-01 1.20000000e+01 4.55000000e+02]
[3.28298657e-01 1.20000000e+01 4.56000000e+02]
[2.51272722e-01 1.20000000e+01 4.57000000e+02]
[1.74041449e-01 1.20000000e+01 4.58000000e+02]
[1.15206364e-01 1.20000000e+01 4.59000000e+02]
[6.02542571e-02 1.20000000e+01 4.60000000e+02]
[3.46188782e-02 1.20000000e+01 4.61000000e+02]
[2.67543826e-02 1.20000000e+01 4.62000000e+02]
[2.65335401e-02 1.20000000e+01 4.63000000e+02]
[3.42423899e-02 1.20000000e+01 4.64000000e+02]
[4.8370613e-02 1.2000000e+01 4.6500000e+02]
[6.90473136e-02 1.20000000e+01 4.66000000e+02]
[9.36180389e-02 1.20000000e+01 4.67000000e+02]
[1.19212721e-01 1.20000000e+01 4.68000000e+02]
[1.50106811e-01 1.20000000e+01 4.69000000e+02]
[1.80021784e-01 1.20000000e+01 4.70000000e+02]
[2.06641

[ 0.09825876 13.         59.        ]
[ 0.09701427 13.         60.        ]
[ 0.0955671 13.        61.       ]
[ 0.09135854 13.         62.        ]
[ 0.08697317 13.         63.        ]
[ 0.08317541 13.         64.        ]
[ 0.07809483 13.         65.        ]
[ 0.07251423 13.         66.        ]
[6.60111483e-02 1.30000000e+01 6.70000000e+01]
[5.96256797e-02 1.30000000e+01 6.80000000e+01]
[5.29121181e-02 1.30000000e+01 6.90000000e+01]
[4.4491355e-02 1.3000000e+01 7.0000000e+01]
[3.60887673e-02 1.30000000e+01 7.10000000e+01]
[2.75936193e-02 1.30000000e+01 7.20000000e+01]
[1.90596585e-02 1.30000000e+01 7.30000000e+01]
[1.12215743e-02 1.30000000e+01 7.40000000e+01]
[4.73897035e-03 1.30000000e+01 7.50000000e+01]
[6.16323856e-04 1.30000000e+01 7.60000000e+01]
[4.87522261e-04 1.30000000e+01 7.70000000e+01]
[5.31674149e-03 1.30000000e+01 7.80000000e+01]
[1.61413473e-02 1.30000000e+01 7.90000000e+01]
[3.26596288e-02 1.30000000e+01 8.00000000e+01]
[5.42077419e-02 1.30000000e+01 8.10000000e+0

[  0.52161883  13.         248.        ]
[  0.52229681  13.         249.        ]
[  0.5226417  13.        250.       ]
[  0.52276511  13.         251.        ]
[  0.52267723  13.         252.        ]
[  0.52231496  13.         253.        ]
[  0.5217117  13.        254.       ]
[  0.52088189  13.         255.        ]
[  0.52005774  13.         256.        ]
[  0.5195245  13.        257.       ]
[  0.51960916  13.         258.        ]
[  0.5200236  13.        259.       ]
[  0.52060922  13.         260.        ]
[  0.52116067  13.         261.        ]
[  0.52155103  13.         262.        ]
[  0.5220397  13.        263.       ]
[  0.52244423  13.         264.        ]
[  0.52286768  13.         265.        ]
[  0.52331361  13.         266.        ]
[  0.52371276  13.         267.        ]
[  0.52410139  13.         268.        ]
[  0.52444932  13.         269.        ]
[  0.52476379  13.         270.        ]
[  0.52509742  13.         271.        ]
[  0.52541821  13.         272.

[9.93803269e-04 1.30000000e+01 5.29000000e+02]
[1.30145604e-04 1.30000000e+01 5.30000000e+02]
[4.04701749e-03 1.30000000e+01 5.31000000e+02]
[1.62809071e-02 1.30000000e+01 5.32000000e+02]
[3.79226329e-02 1.30000000e+01 5.33000000e+02]
[7.41296076e-02 1.30000000e+01 5.34000000e+02]
[1.22350638e-01 1.30000000e+01 5.35000000e+02]
[1.71813935e-01 1.30000000e+01 5.36000000e+02]
[2.24127243e-01 1.30000000e+01 5.37000000e+02]
[2.72056289e-01 1.30000000e+01 5.38000000e+02]
[3.07164943e-01 1.30000000e+01 5.39000000e+02]
[3.18500712e-01 1.30000000e+01 5.40000000e+02]
[3.19928785e-01 1.30000000e+01 5.41000000e+02]
[3.19195839e-01 1.30000000e+01 5.42000000e+02]
[3.19290961e-01 1.30000000e+01 5.43000000e+02]
[3.17407313e-01 1.30000000e+01 5.44000000e+02]
[3.09251036e-01 1.30000000e+01 5.45000000e+02]
[2.9570229e-01 1.3000000e+01 5.4600000e+02]
[2.75646337e-01 1.30000000e+01 5.47000000e+02]
[2.49643052e-01 1.30000000e+01 5.48000000e+02]
[2.08512077e-01 1.30000000e+01 5.49000000e+02]
[1.58752637e-01 

[6.62925419e-03 1.40000000e+01 1.53000000e+02]
[7.88365887e-03 1.40000000e+01 1.54000000e+02]
[9.02669289e-03 1.40000000e+01 1.55000000e+02]
[1.00606357e-02 1.40000000e+01 1.56000000e+02]
[1.08924903e-02 1.40000000e+01 1.57000000e+02]
[1.15982343e-02 1.40000000e+01 1.58000000e+02]
[1.23610778e-02 1.40000000e+01 1.59000000e+02]
[1.3152794e-02 1.4000000e+01 1.6000000e+02]
[1.40953494e-02 1.40000000e+01 1.61000000e+02]
[1.51691959e-02 1.40000000e+01 1.62000000e+02]
[1.64672013e-02 1.40000000e+01 1.63000000e+02]
[1.80810997e-02 1.40000000e+01 1.64000000e+02]
[2.00564051e-02 1.40000000e+01 1.65000000e+02]
[2.22879267e-02 1.40000000e+01 1.66000000e+02]
[2.4890255e-02 1.4000000e+01 1.6700000e+02]
[2.77388595e-02 1.40000000e+01 1.68000000e+02]
[3.10973241e-02 1.40000000e+01 1.69000000e+02]
[3.44425398e-02 1.40000000e+01 1.70000000e+02]
[3.77219869e-02 1.40000000e+01 1.71000000e+02]
[4.07807188e-02 1.40000000e+01 1.72000000e+02]
[4.37146632e-02 1.40000000e+01 1.73000000e+02]
[4.65003105e-02 1.4

[  0.54581292  14.         349.        ]
[  0.54578561  14.         350.        ]
[  0.54595648  14.         351.        ]
[  0.54589533  14.         352.        ]
[  0.54611823  14.         353.        ]
[  0.54624999  14.         354.        ]
[  0.54614504  14.         355.        ]
[  0.54610609  14.         356.        ]
[  0.54630286  14.         357.        ]
[  0.54630704  14.         358.        ]
[  0.54609321  14.         359.        ]
[  0.5458605  14.        360.       ]
[  0.54548729  14.         361.        ]
[  0.54517124  14.         362.        ]
[  0.54493961  14.         363.        ]
[  0.54501915  14.         364.        ]
[  0.54481509  14.         365.        ]
[  0.54479647  14.         366.        ]
[  0.54450525  14.         367.        ]
[  0.5444133  14.        368.       ]
[  0.5440695  14.        369.       ]
[  0.54363525  14.         370.        ]
[  0.54357927  14.         371.        ]
[  0.54353378  14.         372.        ]
[  0.54317638  14.       

[7.11919022e-02 1.40000000e+01 5.52000000e+02]
[3.77449368e-02 1.40000000e+01 5.53000000e+02]
[1.59671336e-02 1.40000000e+01 5.54000000e+02]
[7.5828607e-03 1.4000000e+01 5.5500000e+02]
[5.23721573e-03 1.40000000e+01 5.56000000e+02]
[4.00443923e-03 1.40000000e+01 5.57000000e+02]
[5.0576319e-03 1.4000000e+01 5.5800000e+02]
[6.67738225e-03 1.40000000e+01 5.59000000e+02]
[8.30946122e-03 1.40000000e+01 5.60000000e+02]
[1.22904735e-02 1.40000000e+01 5.61000000e+02]
[1.2877836e-02 1.4000000e+01 5.6200000e+02]
[1.23326254e-02 1.40000000e+01 5.63000000e+02]
[1.43695897e-02 1.40000000e+01 5.64000000e+02]
[2.53772027e-02 1.40000000e+01 5.65000000e+02]
[3.93805483e-02 1.40000000e+01 5.66000000e+02]
[5.46730076e-02 1.40000000e+01 5.67000000e+02]
[6.72270092e-02 1.40000000e+01 5.68000000e+02]
[8.41415909e-02 1.40000000e+01 5.69000000e+02]
[9.27889934e-02 1.40000000e+01 5.70000000e+02]
[1.03335332e-01 1.40000000e+01 5.71000000e+02]
[1.14869707e-01 1.40000000e+01 5.72000000e+02]
[1.33121557e-01 1.4000

[8.61747735e-02 1.50000000e+01 1.90000000e+02]
[8.64118719e-02 1.50000000e+01 1.91000000e+02]
[8.58888587e-02 1.50000000e+01 1.92000000e+02]
[8.4335541e-02 1.5000000e+01 1.9300000e+02]
[8.12597414e-02 1.50000000e+01 1.94000000e+02]
[7.69158508e-02 1.50000000e+01 1.95000000e+02]
[7.15317568e-02 1.50000000e+01 1.96000000e+02]
[6.56381347e-02 1.50000000e+01 1.97000000e+02]
[5.85776723e-02 1.50000000e+01 1.98000000e+02]
[5.02217654e-02 1.50000000e+01 1.99000000e+02]
[4.06431981e-02 1.50000000e+01 2.00000000e+02]
[3.02179493e-02 1.50000000e+01 2.01000000e+02]
[1.9243576e-02 1.5000000e+01 2.0200000e+02]
[9.02905323e-03 1.50000000e+01 2.03000000e+02]
[1.77930167e-03 1.50000000e+01 2.04000000e+02]
[3.9686904e-04 1.5000000e+01 2.0500000e+02]
[7.8829183e-03 1.5000000e+01 2.0600000e+02]
[2.62557478e-02 1.50000000e+01 2.07000000e+02]
[5.57831895e-02 1.50000000e+01 2.08000000e+02]
[9.32177791e-02 1.50000000e+01 2.09000000e+02]
[1.3445543e-01 1.5000000e+01 2.1000000e+02]
[1.75594855e-01 1.50000000e+

[  0.54860737  15.         437.        ]
[  0.54837329  15.         438.        ]
[  0.54739272  15.         439.        ]
[  0.54559088  15.         440.        ]
[  0.54138907  15.         441.        ]
[  0.54212432  15.         442.        ]
[  0.53938382  15.         443.        ]
[  0.5454513  15.        444.       ]
[  0.55243964  15.         445.        ]
[  0.56148886  15.         446.        ]
[  0.57891501  15.         447.        ]
[  0.59653991  15.         448.        ]
[  0.6076714  15.        449.       ]
[  0.60879628  15.         450.        ]
[  0.593996  15.       451.      ]
[  0.56349663  15.         452.        ]
[  0.51859068  15.         453.        ]
[  0.46155074  15.         454.        ]
[4.0088135e-01 1.5000000e+01 4.5500000e+02]
[3.27497604e-01 1.50000000e+01 4.56000000e+02]
[2.50278243e-01 1.50000000e+01 4.57000000e+02]
[1.73019487e-01 1.50000000e+01 4.58000000e+02]
[1.14296166e-01 1.50000000e+01 4.59000000e+02]
[5.9486503e-02 1.5000000e+01 4.6000000e+02

[  0.27901065  16.         101.        ]
[  0.27604644  16.         102.        ]
[  0.27285103  16.         103.        ]
[  0.27006874  16.         104.        ]
[  0.26686933  16.         105.        ]
[  0.26354806  16.         106.        ]
[  0.25942938  16.         107.        ]
[  0.25482792  16.         108.        ]
[  0.24888409  16.         109.        ]
[  0.24185131  16.         110.        ]
[  0.2336103  16.        111.       ]
[  0.22407167  16.         112.        ]
[  0.21337962  16.         113.        ]
[  0.20148002  16.         114.        ]
[  0.18839697  16.         115.        ]
[  0.17476783  16.         116.        ]
[  0.16022723  16.         117.        ]
[  0.14557699  16.         118.        ]
[  0.13040302  16.         119.        ]
[1.15610414e-01 1.60000000e+01 1.20000000e+02]
[1.01169264e-01 1.60000000e+01 1.21000000e+02]
[8.7864722e-02 1.6000000e+01 1.2200000e+02]
[7.53641244e-02 1.60000000e+01 1.23000000e+02]
[6.40209716e-02 1.60000000e+01 1.240000

[  0.5527551  16.        351.       ]
[  0.55269345  16.         352.        ]
[  0.55291422  16.         353.        ]
[  0.55304421  16.         354.        ]
[  0.5529377  16.        355.       ]
[  0.55290024  16.         356.        ]
[  0.55309801  16.         357.        ]
[  0.55310172  16.         358.        ]
[  0.55287717  16.         359.        ]
[  0.55262173  16.         360.        ]
[  0.55221795  16.         361.        ]
[  0.55186499  16.         362.        ]
[  0.55160634  16.         363.        ]
[  0.55166241  16.         364.        ]
[  0.5514451  16.        365.       ]
[  0.5514213  16.        366.       ]
[  0.55112139  16.         367.        ]
[  0.55102209  16.         368.        ]
[  0.55068024  16.         369.        ]
[  0.55026268  16.         370.        ]
[  0.55022946  16.         371.        ]
[  0.55020712  16.         372.        ]
[  0.54986582  16.         373.        ]
[  0.54921653  16.         374.        ]
[  0.54858613  16.         3

[5.29511573e-03 1.70000000e+01 1.80000000e+01]
[5.95633991e-05 1.70000000e+01 1.90000000e+01]
[3.62438628e-05 1.70000000e+01 2.00000000e+01]
[5.19092596e-04 1.70000000e+01 2.10000000e+01]
[4.31918049e-03 1.70000000e+01 2.20000000e+01]
[1.33564356e-02 1.70000000e+01 2.30000000e+01]
[1.99616454e-02 1.70000000e+01 2.40000000e+01]
[ 0.02931803 17.         25.        ]
[ 0.04347568 17.         26.        ]
[ 0.05530402 17.         27.        ]
[ 0.0667431 17.        28.       ]
[ 0.07723883 17.         29.        ]
[ 0.08496998 17.         30.        ]
[ 0.08891428 17.         31.        ]
[ 0.09091536 17.         32.        ]
[ 0.09284301 17.         33.        ]
[ 0.09542327 17.         34.        ]
[ 0.09543632 17.         35.        ]
[ 0.09976539 17.         36.        ]
[ 0.10110289 17.         37.        ]
[ 0.10156038 17.         38.        ]
[ 0.10369992 17.         39.        ]
[ 0.10685797 17.         40.        ]
[ 0.10985821 17.         41.        ]
[ 0.11175898 17.         42.

[  0.54477217  17.         299.        ]
[  0.54498006  17.         300.        ]
[  0.54518968  17.         301.        ]
[  0.54533485  17.         302.        ]
[  0.54555232  17.         303.        ]
[  0.54586082  17.         304.        ]
[  0.54609833  17.         305.        ]
[  0.5463694  17.        306.       ]
[  0.5466648  17.        307.       ]
[  0.54698669  17.         308.        ]
[  0.54734003  17.         309.        ]
[  0.54771086  17.         310.        ]
[  0.54801287  17.         311.        ]
[  0.54830526  17.         312.        ]
[  0.54849703  17.         313.        ]
[  0.54859786  17.         314.        ]
[  0.54889149  17.         315.        ]
[  0.54915479  17.         316.        ]
[  0.54940566  17.         317.        ]
[  0.54975743  17.         318.        ]
[  0.54998467  17.         319.        ]
[  0.55029634  17.         320.        ]
[  0.55060844  17.         321.        ]
[  0.55080488  17.         322.        ]
[  0.55104809  17.    

[6.17279282e-03 1.80000000e+01 6.00000000e+00]
[3.58579695e-03 1.80000000e+01 7.00000000e+00]
[1.58507454e-03 1.80000000e+01 8.00000000e+00]
[5.91001917e-04 1.80000000e+01 9.00000000e+00]
[8.09640067e-05 1.80000000e+01 1.00000000e+01]
[2.3652295e-04 1.8000000e+01 1.1000000e+01]
[2.36007959e-03 1.80000000e+01 1.20000000e+01]
[5.23722723e-03 1.80000000e+01 1.30000000e+01]
[5.41902717e-03 1.80000000e+01 1.40000000e+01]
[7.71384329e-03 1.80000000e+01 1.50000000e+01]
[8.15699933e-03 1.80000000e+01 1.60000000e+01]
[5.29511573e-03 1.80000000e+01 1.70000000e+01]
[ 0. 18. 18.]
[7.56366848e-03 1.80000000e+01 1.90000000e+01]
[2.3392809e-03 1.8000000e+01 2.0000000e+01]
[3.42862846e-03 1.80000000e+01 2.10000000e+01]
[1.09345232e-02 1.80000000e+01 2.20000000e+01]
[ 0.02480938 18.         23.        ]
[ 0.0328646 18.        24.       ]
[ 0.04425498 18.         25.        ]
[ 0.06127808 18.         26.        ]
[ 0.07470415 18.         27.        ]
[ 0.08737144 18.         28.        ]
[ 0.09848493 18

[  0.54708379  18.         298.        ]
[  0.54740518  18.         299.        ]
[  0.54761482  18.         300.        ]
[  0.54782751  18.         301.        ]
[  0.54797492  18.         302.        ]
[  0.54819436  18.         303.        ]
[  0.54850402  18.         304.        ]
[  0.54874266  18.         305.        ]
[  0.54901409  18.         306.        ]
[  0.54931057  18.         307.        ]
[  0.54963492  18.         308.        ]
[  0.54998932  18.         309.        ]
[  0.55035988  18.         310.        ]
[  0.55066149  18.         311.        ]
[  0.55095302  18.         312.        ]
[  0.55114371  18.         313.        ]
[  0.55124286  18.         314.        ]
[  0.55153542  18.         315.        ]
[  0.55179807  18.         316.        ]
[  0.55204852  18.         317.        ]
[  0.55239956  18.         318.        ]
[  0.55262565  18.         319.        ]
[  0.5529357  18.        320.       ]
[  0.55324792  18.         321.        ]
[  0.55344425  18. 

[1.60992515e-01 1.80000000e+01 5.80000000e+02]
[1.65341174e-01 1.80000000e+01 5.81000000e+02]
[1.69833457e-01 1.80000000e+01 5.82000000e+02]
[1.7446675e-01 1.8000000e+01 5.8300000e+02]
[ 0.03523162 19.          0.        ]
[ 0.02908241 19.          1.        ]
[ 0.0233449 19.         2.       ]
[1.81659814e-02 1.90000000e+01 3.00000000e+00]
[1.36330296e-02 1.90000000e+01 4.00000000e+00]
[9.78207632e-03 1.90000000e+01 5.00000000e+00]
[6.61111735e-03 1.90000000e+01 6.00000000e+00]
[4.09497101e-03 1.90000000e+01 7.00000000e+00]
[2.08642292e-03 1.90000000e+01 8.00000000e+00]
[1.0204201e-03 1.9000000e+01 9.0000000e+00]
[3.51674222e-04 1.90000000e+01 1.00000000e+01]
[3.65138917e-06 1.90000000e+01 1.10000000e+01]
[8.57900454e-04 1.90000000e+01 1.20000000e+01]
[2.17756513e-03 1.90000000e+01 1.30000000e+01]
[1.76847452e-03 1.90000000e+01 1.40000000e+01]
[1.99488058e-03 1.90000000e+01 1.50000000e+01]
[9.78132347e-04 1.90000000e+01 1.60000000e+01]
[5.95633991e-05 1.90000000e+01 1.70000000e+01]
[7

[5.26190314e-02 1.90000000e+01 1.99000000e+02]
[4.28103571e-02 1.90000000e+01 2.00000000e+02]
[3.20400365e-02 1.90000000e+01 2.01000000e+02]
[2.05659869e-02 1.90000000e+01 2.02000000e+02]
[9.73328282e-03 1.90000000e+01 2.03000000e+02]
[1.93167258e-03 1.90000000e+01 2.04000000e+02]
[4.43824229e-04 1.90000000e+01 2.05000000e+02]
[8.81105038e-03 1.90000000e+01 2.06000000e+02]
[2.95190687e-02 1.90000000e+01 2.07000000e+02]
[6.29328624e-02 1.90000000e+01 2.08000000e+02]
[1.05211051e-01 1.90000000e+01 2.09000000e+02]
[1.51404713e-01 1.90000000e+01 2.10000000e+02]
[1.96894951e-01 1.90000000e+01 2.11000000e+02]
[  0.23927712  19.         212.        ]
[  0.27742912  19.         213.        ]
[  0.31122436  19.         214.        ]
[  0.34224829  19.         215.        ]
[  0.37089316  19.         216.        ]
[  0.39693065  19.         217.        ]
[  0.41916011  19.         218.        ]
[  0.43771849  19.         219.        ]
[  0.45302626  19.         220.        ]
[  0.46620844  19.  

[3.89680992e-01 1.90000000e+01 4.94000000e+02]
[3.89929695e-01 1.90000000e+01 4.95000000e+02]
[3.90738046e-01 1.90000000e+01 4.96000000e+02]
[3.93340879e-01 1.90000000e+01 4.97000000e+02]
[3.91821881e-01 1.90000000e+01 4.98000000e+02]
[3.90544529e-01 1.90000000e+01 4.99000000e+02]
[3.87346975e-01 1.90000000e+01 5.00000000e+02]
[3.83129897e-01 1.90000000e+01 5.01000000e+02]
[3.76187531e-01 1.90000000e+01 5.02000000e+02]
[3.70654815e-01 1.90000000e+01 5.03000000e+02]
[3.65442701e-01 1.90000000e+01 5.04000000e+02]
[3.59433534e-01 1.90000000e+01 5.05000000e+02]
[3.53246359e-01 1.90000000e+01 5.06000000e+02]
[3.47484465e-01 1.90000000e+01 5.07000000e+02]
[3.36669719e-01 1.90000000e+01 5.08000000e+02]
[3.24535999e-01 1.90000000e+01 5.09000000e+02]
[3.08798033e-01 1.90000000e+01 5.10000000e+02]
[2.91397198e-01 1.90000000e+01 5.11000000e+02]
[2.65509482e-01 1.90000000e+01 5.12000000e+02]
[2.42144721e-01 1.90000000e+01 5.13000000e+02]
[2.14981989e-01 1.90000000e+01 5.14000000e+02]
[1.9179637e-0

[3.96384258e-04 2.00000000e+01 1.47000000e+02]
[1.01923624e-03 2.00000000e+01 1.48000000e+02]
[1.89418909e-03 2.00000000e+01 1.49000000e+02]
[3.05433607e-03 2.00000000e+01 1.50000000e+02]
[4.42607059e-03 2.00000000e+01 1.51000000e+02]
[5.91337994e-03 2.00000000e+01 1.52000000e+02]
[7.41774675e-03 2.00000000e+01 1.53000000e+02]
[8.80022843e-03 2.00000000e+01 1.54000000e+02]
[1.00575294e-02 2.00000000e+01 1.55000000e+02]
[1.11944365e-02 2.00000000e+01 1.56000000e+02]
[1.21097687e-02 2.00000000e+01 1.57000000e+02]
[1.28846542e-02 2.00000000e+01 1.58000000e+02]
[1.37226992e-02 2.00000000e+01 1.59000000e+02]
[1.45898651e-02 2.00000000e+01 1.60000000e+02]
[1.56195431e-02 2.00000000e+01 1.61000000e+02]
[1.67890377e-02 2.00000000e+01 1.62000000e+02]
[1.81983135e-02 2.00000000e+01 1.63000000e+02]
[1.99479392e-02 2.00000000e+01 1.64000000e+02]
[2.20796543e-02 2.00000000e+01 1.65000000e+02]
[2.44777516e-02 2.00000000e+01 1.66000000e+02]
[2.72676299e-02 2.00000000e+01 1.67000000e+02]
[3.03098591e-

[  0.55893437  20.         383.        ]
[  0.56011499  20.         384.        ]
[  0.56141298  20.         385.        ]
[  0.56284601  20.         386.        ]
[  0.56361203  20.         387.        ]
[  0.56407935  20.         388.        ]
[  0.56489055  20.         389.        ]
[  0.56541576  20.         390.        ]
[  0.56543558  20.         391.        ]
[  0.56537443  20.         392.        ]
[  0.56537637  20.         393.        ]
[  0.56536262  20.         394.        ]
[  0.56621623  20.         395.        ]
[  0.56634487  20.         396.        ]
[  0.56723677  20.         397.        ]
[  0.56760759  20.         398.        ]
[  0.56799285  20.         399.        ]
[  0.56964452  20.         400.        ]
[  0.57083956  20.         401.        ]
[  0.57192474  20.         402.        ]
[  0.57245606  20.         403.        ]
[  0.57285169  20.         404.        ]
[  0.57269174  20.         405.        ]
[  0.57285667  20.         406.        ]
[  0.57237672  2

[ 0.13341969 21.         62.        ]
[ 0.12658999 21.         63.        ]
[ 0.12068703 21.         64.        ]
[ 0.1132281 21.        65.       ]
[ 0.10495499 21.         66.        ]
[ 0.09565742 21.         67.        ]
[ 0.08650247 21.         68.        ]
[ 0.07684446 21.         69.        ]
[6.48560321e-02 2.10000000e+01 7.00000000e+01]
[5.29526869e-02 2.10000000e+01 7.10000000e+01]
[4.0939523e-02 2.1000000e+01 7.2000000e+01]
[2.87897417e-02 2.10000000e+01 7.30000000e+01]
[1.74262739e-02 2.10000000e+01 7.40000000e+01]
[7.79354685e-03 2.10000000e+01 7.50000000e+01]
[1.3022048e-03 2.1000000e+01 7.6000000e+01]
[3.91480432e-04 2.10000000e+01 7.70000000e+01]
[6.44610484e-03 2.10000000e+01 7.80000000e+01]
[2.08482731e-02 2.10000000e+01 7.90000000e+01]
[4.29517113e-02 2.10000000e+01 8.00000000e+01]
[7.14466267e-02 2.10000000e+01 8.10000000e+01]
[ 0.1023108 21.        82.       ]
[ 0.13530594 21.         83.        ]
[ 0.16739035 21.         84.        ]
[ 0.19751027 21.         85.  

[  0.54562967  21.         252.        ]
[  0.54523989  21.         253.        ]
[  0.54461829  21.         254.        ]
[  0.54378123  21.         255.        ]
[  0.54296276  21.         256.        ]
[  0.5424112  21.        257.       ]
[  0.54247924  21.         258.        ]
[  0.54288036  21.         259.        ]
[  0.54345062  21.         260.        ]
[  0.5439926  21.        261.       ]
[  0.54437239  21.         262.        ]
[  0.54485315  21.         263.        ]
[  0.54524254  21.         264.        ]
[  0.54565701  21.         265.        ]
[  0.54609182  21.         266.        ]
[  0.54648028  21.         267.        ]
[  0.54685832  21.         268.        ]
[  0.54720205  21.         269.        ]
[  0.54750741  21.         270.        ]
[  0.54783314  21.         271.        ]
[  0.54814334  21.         272.        ]
[  0.54846988  21.         273.        ]
[  0.54873089  21.         274.        ]
[  0.54894627  21.         275.        ]
[  0.54926008  21.    

[8.92925139e-04 2.10000000e+01 5.29000000e+02]
[1.69060733e-04 2.10000000e+01 5.30000000e+02]
[4.23425091e-03 2.10000000e+01 5.31000000e+02]
[1.6571009e-02 2.1000000e+01 5.3200000e+02]
[3.82190217e-02 2.10000000e+01 5.33000000e+02]
[7.42985578e-02 2.10000000e+01 5.34000000e+02]
[1.22202064e-01 2.10000000e+01 5.35000000e+02]
[1.71245242e-01 2.10000000e+01 5.36000000e+02]
[2.23078099e-01 2.10000000e+01 5.37000000e+02]
[2.7041885e-01 2.1000000e+01 5.3800000e+02]
[3.04676215e-01 2.10000000e+01 5.39000000e+02]
[3.15247857e-01 2.10000000e+01 5.40000000e+02]
[3.16314163e-01 2.10000000e+01 5.41000000e+02]
[3.15764874e-01 2.10000000e+01 5.42000000e+02]
[3.1608735e-01 2.1000000e+01 5.4300000e+02]
[3.14187124e-01 2.10000000e+01 5.44000000e+02]
[3.05989689e-01 2.10000000e+01 5.45000000e+02]
[2.9223266e-01 2.1000000e+01 5.4600000e+02]
[2.72246544e-01 2.10000000e+01 5.47000000e+02]
[2.46416072e-01 2.10000000e+01 5.48000000e+02]
[2.05673302e-01 2.10000000e+01 5.49000000e+02]
[1.56642337e-01 2.1000000

[  0.50129545  22.         223.        ]
[  0.50860647  22.         224.        ]
[  0.51457448  22.         225.        ]
[  0.5195303  22.        226.       ]
[  0.52373848  22.         227.        ]
[  0.52752626  22.         228.        ]
[  0.53097658  22.         229.        ]
[  0.53411973  22.         230.        ]
[  0.53681974  22.         231.        ]
[  0.53875533  22.         232.        ]
[  0.54020372  22.         233.        ]
[  0.54128379  22.         234.        ]
[  0.54224254  22.         235.        ]
[  0.54294195  22.         236.        ]
[  0.54345786  22.         237.        ]
[  0.5438408  22.        238.       ]
[  0.54405143  22.         239.        ]
[  0.54417777  22.         240.        ]
[  0.54409987  22.         241.        ]
[  0.54393724  22.         242.        ]
[  0.54376587  22.         243.        ]
[  0.5440531  22.        244.       ]
[  0.54467283  22.         245.        ]
[  0.54556691  22.         246.        ]
[  0.54658974  22.       

[3.16535745e-01 2.20000000e+01 5.10000000e+02]
[2.98745874e-01 2.20000000e+01 5.11000000e+02]
[2.72483567e-01 2.20000000e+01 5.12000000e+02]
[2.48768452e-01 2.20000000e+01 5.13000000e+02]
[2.21015184e-01 2.20000000e+01 5.14000000e+02]
[1.97322311e-01 2.20000000e+01 5.15000000e+02]
[1.71284571e-01 2.20000000e+01 5.16000000e+02]
[1.47373141e-01 2.20000000e+01 5.17000000e+02]
[1.2501717e-01 2.2000000e+01 5.1800000e+02]
[1.04245846e-01 2.20000000e+01 5.19000000e+02]
[8.79017796e-02 2.20000000e+01 5.20000000e+02]
[7.25122572e-02 2.20000000e+01 5.21000000e+02]
[5.85635478e-02 2.20000000e+01 5.22000000e+02]
[4.59502562e-02 2.20000000e+01 5.23000000e+02]
[3.46306611e-02 2.20000000e+01 5.24000000e+02]
[2.44033883e-02 2.20000000e+01 5.25000000e+02]
[1.64085604e-02 2.20000000e+01 5.26000000e+02]
[9.92563265e-03 2.20000000e+01 5.27000000e+02]
[4.70331471e-03 2.20000000e+01 5.28000000e+02]
[1.06855792e-03 2.20000000e+01 5.29000000e+02]
[1.0671174e-04 2.2000000e+01 5.3000000e+02]
[3.91559856e-03 2.2

[  0.27078712  23.         212.        ]
[  0.30976553  23.         213.        ]
[  0.34350401  23.         214.        ]
[  0.37384705  23.         215.        ]
[  0.4013574  23.        216.       ]
[  0.42593561  23.         217.        ]
[  0.44651034  23.         218.        ]
[  0.46335456  23.         219.        ]
[  0.47694098  23.         220.        ]
[  0.48848284  23.         221.        ]
[  0.49837907  23.         222.        ]
[  0.50667462  23.         223.        ]
[  0.51363371  23.         224.        ]
[  0.51929242  23.         225.        ]
[  0.52397738  23.         226.        ]
[  0.52794745  23.         227.        ]
[  0.5315239  23.        228.       ]
[  0.53478437  23.         229.        ]
[  0.53776013  23.         230.        ]
[  0.54031291  23.         231.        ]
[  0.54211958  23.         232.        ]
[  0.54345585  23.         233.        ]
[  0.54443734  23.         234.        ]
[  0.54530833  23.         235.        ]
[  0.54593047  23.    

[3.51427323e-01 2.30000000e+01 4.80000000e+02]
[3.59542814e-01 2.30000000e+01 4.81000000e+02]
[3.67092863e-01 2.30000000e+01 4.82000000e+02]
[3.7364241e-01 2.3000000e+01 4.8300000e+02]
[3.79630872e-01 2.30000000e+01 4.84000000e+02]
[3.83245017e-01 2.30000000e+01 4.85000000e+02]
[3.89192961e-01 2.30000000e+01 4.86000000e+02]
[3.91938765e-01 2.30000000e+01 4.87000000e+02]
[3.9259302e-01 2.3000000e+01 4.8800000e+02]
[3.93537032e-01 2.30000000e+01 4.89000000e+02]
[3.94929294e-01 2.30000000e+01 4.90000000e+02]
[3.97627506e-01 2.30000000e+01 4.91000000e+02]
[4.00071756e-01 2.30000000e+01 4.92000000e+02]
[4.03256613e-01 2.30000000e+01 4.93000000e+02]
[4.03915239e-01 2.30000000e+01 4.94000000e+02]
[4.04017262e-01 2.30000000e+01 4.95000000e+02]
[4.04807867e-01 2.30000000e+01 4.96000000e+02]
[4.07104862e-01 2.30000000e+01 4.97000000e+02]
[4.05456482e-01 2.30000000e+01 4.98000000e+02]
[4.04252294e-01 2.30000000e+01 4.99000000e+02]
[4.0093841e-01 2.3000000e+01 5.0000000e+02]
[3.96689939e-01 2.3000

[ 0.19707041 24.         84.        ]
[ 0.22778662 24.         85.        ]
[ 0.25454391 24.         86.        ]
[ 0.27714162 24.         87.        ]
[ 0.2957498 24.        88.       ]
[ 0.31110358 24.         89.        ]
[ 0.32340569 24.         90.        ]
[ 0.33286471 24.         91.        ]
[ 0.33984668 24.         92.        ]
[ 0.34464275 24.         93.        ]
[ 0.34739495 24.         94.        ]
[ 0.34799412 24.         95.        ]
[ 0.34713223 24.         96.        ]
[ 0.34543233 24.         97.        ]
[ 0.34274106 24.         98.        ]
[ 0.33977223 24.         99.        ]
[  0.33604871  24.         100.        ]
[  0.33218606  24.         101.        ]
[  0.32873959  24.         102.        ]
[  0.32509935  24.         103.        ]
[  0.3219952  24.        104.       ]
[  0.31858023  24.         105.        ]
[  0.31511876  24.         106.        ]
[  0.31088768  24.         107.        ]
[  0.30624524  24.         108.        ]
[  0.30024626  24.         10

[  0.57042909  24.         354.        ]
[  0.57033853  24.         355.        ]
[  0.57032073  24.         356.        ]
[  0.57050978  24.         357.        ]
[  0.57048233  24.         358.        ]
[  0.57018324  24.         359.        ]
[  0.56980777  24.         360.        ]
[  0.56927449  24.         361.        ]
[  0.56876676  24.         362.        ]
[  0.56844175  24.         363.        ]
[  0.56842605  24.         364.        ]
[  0.56815399  24.         365.        ]
[  0.5681188  24.        366.       ]
[  0.56779318  24.         367.        ]
[  0.56768332  24.         368.        ]
[  0.56734017  24.         369.        ]
[  0.5669475  24.        370.       ]
[  0.56691346  24.         371.        ]
[  0.5669292  24.        372.       ]
[  0.56657161  24.         373.        ]
[  0.56592236  24.         374.        ]
[  0.5652588  24.        375.       ]
[  0.56489696  24.         376.        ]
[  0.56494618  24.         377.        ]
[  0.56454874  24.         3

[2.40235177e-01 2.40000000e+01 5.48000000e+02]
[1.9891127e-01 2.4000000e+01 5.4900000e+02]
[1.49631224e-01 2.40000000e+01 5.50000000e+02]
[1.04144962e-01 2.40000000e+01 5.51000000e+02]
[6.47762155e-02 2.40000000e+01 5.52000000e+02]
[3.30898631e-02 2.40000000e+01 5.53000000e+02]
[1.30075665e-02 2.40000000e+01 5.54000000e+02]
[5.59024524e-03 2.40000000e+01 5.55000000e+02]
[3.61907693e-03 2.40000000e+01 5.56000000e+02]
[2.59624644e-03 2.40000000e+01 5.57000000e+02]
[3.43196328e-03 2.40000000e+01 5.58000000e+02]
[4.74046046e-03 2.40000000e+01 5.59000000e+02]
[6.09363577e-03 2.40000000e+01 5.60000000e+02]
[9.51952471e-03 2.40000000e+01 5.61000000e+02]
[1.00320523e-02 2.40000000e+01 5.62000000e+02]
[9.53195567e-03 2.40000000e+01 5.63000000e+02]
[1.13201699e-02 2.40000000e+01 5.64000000e+02]
[2.11608171e-02 2.40000000e+01 5.65000000e+02]
[3.39584066e-02 2.40000000e+01 5.66000000e+02]
[4.82145711e-02 2.40000000e+01 5.67000000e+02]
[6.0171496e-02 2.4000000e+01 5.6800000e+02]
[7.65723622e-02 2.4

[  0.5513183  25.        248.       ]
[  0.5518601  25.        249.       ]
[  0.55210638  25.         250.        ]
[  0.55216785  25.         251.        ]
[  0.55204917  25.         252.        ]
[  0.55167894  25.         253.        ]
[  0.55108702  25.         254.        ]
[  0.5502904  25.        255.       ]
[  0.54950674  25.         256.        ]
[  0.54895869  25.         257.        ]
[  0.54901799  25.         258.        ]
[  0.54940403  25.         259.        ]
[  0.54995565  25.         260.        ]
[  0.5504833  25.        261.       ]
[  0.55084828  25.         262.        ]
[  0.55131255  25.         263.        ]
[  0.55168411  25.         264.        ]
[  0.55208551  25.         265.        ]
[  0.55250454  25.         266.        ]
[  0.55287968  25.         267.        ]
[  0.55324312  25.         268.        ]
[  0.55357948  25.         269.        ]
[  0.55387324  25.         270.        ]
[  0.55419008  25.         271.        ]
[  0.55449009  25.         2

[6.44119407e-02 2.50000000e+01 5.22000000e+02]
[5.10928747e-02 2.50000000e+01 5.23000000e+02]
[3.90650552e-02 2.50000000e+01 5.24000000e+02]
[2.81041105e-02 2.50000000e+01 5.25000000e+02]
[1.94223932e-02 2.50000000e+01 5.26000000e+02]
[1.22574266e-02 2.50000000e+01 5.27000000e+02]
[6.31270865e-03 2.50000000e+01 5.28000000e+02]
[1.8741196e-03 2.5000000e+01 5.2900000e+02]
[9.77916777e-09 2.50000000e+01 5.30000000e+02]
[2.79699734e-03 2.50000000e+01 5.31000000e+02]
[1.386576e-02 2.500000e+01 5.320000e+02]
[3.45585386e-02 2.50000000e+01 5.33000000e+02]
[7.00080553e-02 2.50000000e+01 5.34000000e+02]
[1.17715527e-01 2.50000000e+01 5.35000000e+02]
[1.66897592e-01 2.50000000e+01 5.36000000e+02]
[2.19017252e-01 2.50000000e+01 5.37000000e+02]
[2.66682703e-01 2.50000000e+01 5.38000000e+02]
[3.0101931e-01 2.5000000e+01 5.3900000e+02]
[3.11285323e-01 2.50000000e+01 5.40000000e+02]
[3.11868047e-01 2.50000000e+01 5.41000000e+02]
[3.11061477e-01 2.50000000e+01 5.42000000e+02]
[3.11124412e-01 2.5000000

[  0.46191725  26.         218.        ]
[  0.47696716  26.         219.        ]
[  0.48896132  26.         220.        ]
[  0.49911337  26.         221.        ]
[  0.50781272  26.         222.        ]
[  0.51510039  26.         223.        ]
[  0.52121211  26.         224.        ]
[  0.526151  26.       225.      ]
[  0.53022262  26.         226.        ]
[  0.53366425  26.         227.        ]
[  0.53677978  26.         228.        ]
[  0.539631  26.       229.      ]
[  0.54225257  26.         230.        ]
[  0.54449913  26.         231.        ]
[  0.54604652  26.         232.        ]
[  0.54716493  26.         233.        ]
[  0.54796031  26.         234.        ]
[  0.54866642  26.         235.        ]
[  0.54914448  26.         236.        ]
[  0.54946437  26.         237.        ]
[  0.54967838  26.         238.        ]
[  0.54974585  26.         239.        ]
[  0.54974821  26.         240.        ]
[  0.54956919  26.         241.        ]
[  0.54933028  26.         2

[4.0991711e-01 2.6000000e+01 5.0000000e+02]
[4.05875121e-01 2.60000000e+01 5.01000000e+02]
[3.98993281e-01 2.60000000e+01 5.02000000e+02]
[3.93638005e-01 2.60000000e+01 5.03000000e+02]
[3.88837137e-01 2.60000000e+01 5.04000000e+02]
[3.83698775e-01 2.60000000e+01 5.05000000e+02]
[3.78349692e-01 2.60000000e+01 5.06000000e+02]
[3.73176248e-01 2.60000000e+01 5.07000000e+02]
[3.63191045e-01 2.60000000e+01 5.08000000e+02]
[3.51486773e-01 2.60000000e+01 5.09000000e+02]
[3.36022869e-01 2.60000000e+01 5.10000000e+02]
[3.18358211e-01 2.60000000e+01 5.11000000e+02]
[2.92061623e-01 2.60000000e+01 5.12000000e+02]
[2.67869406e-01 2.60000000e+01 5.13000000e+02]
[2.39050671e-01 2.60000000e+01 5.14000000e+02]
[2.14137136e-01 2.60000000e+01 5.15000000e+02]
[1.86743453e-01 2.60000000e+01 5.16000000e+02]
[1.61443038e-01 2.60000000e+01 5.17000000e+02]
[1.37728436e-01 2.60000000e+01 5.18000000e+02]
[1.15760072e-01 2.60000000e+01 5.19000000e+02]
[9.84402626e-02 2.60000000e+01 5.20000000e+02]
[8.20230118e-02 

[  0.25015128  27.         116.        ]
[  0.23416065  27.         117.        ]
[  0.21763702  27.         118.        ]
[  0.20002617  27.         119.        ]
[  0.1823327  27.        120.       ]
[  0.16450492  27.         121.        ]
[  0.14756417  27.         122.        ]
[  0.13109189  27.         123.        ]
[1.15556509e-01 2.70000000e+01 1.24000000e+02]
[1.01098672e-01 2.70000000e+01 1.25000000e+02]
[8.80415914e-02 2.70000000e+01 1.26000000e+02]
[7.65302617e-02 2.70000000e+01 1.27000000e+02]
[6.64678766e-02 2.70000000e+01 1.28000000e+02]
[5.74254428e-02 2.70000000e+01 1.29000000e+02]
[4.99382343e-02 2.70000000e+01 1.30000000e+02]
[4.33776443e-02 2.70000000e+01 1.31000000e+02]
[3.78059006e-02 2.70000000e+01 1.32000000e+02]
[3.30640424e-02 2.70000000e+01 1.33000000e+02]
[2.90683921e-02 2.70000000e+01 1.34000000e+02]
[2.59205155e-02 2.70000000e+01 1.35000000e+02]
[2.31132551e-02 2.70000000e+01 1.36000000e+02]
[2.05067696e-02 2.70000000e+01 1.37000000e+02]
[1.79091772e-02 2

[  0.57510305  27.         393.        ]
[  0.57508114  27.         394.        ]
[  0.57591555  27.         395.        ]
[  0.5761057  27.        396.       ]
[  0.57706253  27.         397.        ]
[  0.5774519  27.        398.       ]
[  0.57784215  27.         399.        ]
[  0.57952515  27.         400.        ]
[  0.58073451  27.         401.        ]
[  0.5818604  27.        402.       ]
[  0.58241919  27.         403.        ]
[  0.58281692  27.         404.        ]
[  0.58260148  27.         405.        ]
[  0.58274316  27.         406.        ]
[  0.5822556  27.        407.       ]
[  0.58224012  27.         408.        ]
[  0.58185363  27.         409.        ]
[  0.5811995  27.        410.       ]
[  0.5810174  27.        411.       ]
[  0.5811728  27.        412.       ]
[  0.58180759  27.         413.        ]
[  0.58348003  27.         414.        ]
[  0.58395347  27.         415.        ]
[  0.58405063  27.         416.        ]
[  0.58339059  27.         417.      

[1.66539558e-02 2.80000000e+01 7.70000000e+01]
[3.71575612e-02 2.80000000e+01 7.80000000e+01]
[6.62793447e-02 2.80000000e+01 7.90000000e+01]
[ 0.10110616 28.         80.        ]
[ 0.13931642 28.         81.        ]
[ 0.17598011 28.         82.        ]
[ 0.21207741 28.         83.        ]
[ 0.24485763 28.         84.        ]
[ 0.27422561 28.         85.        ]
[ 0.29911596 28.         86.        ]
[ 0.31968297 28.         87.        ]
[ 0.33631216 28.         88.        ]
[ 0.3498422 28.        89.       ]
[ 0.36048013 28.         90.        ]
[ 0.36856093 28.         91.        ]
[ 0.37438644 28.         92.        ]
[ 0.37825333 28.         93.        ]
[ 0.38026316 28.         94.        ]
[ 0.38029594 28.         95.        ]
[ 0.37900054 28.         96.        ]
[ 0.37699393 28.         97.        ]
[ 0.37410628 28.         98.        ]
[ 0.37100256 28.         99.        ]
[  0.36719079  28.         100.        ]
[  0.36328115  28.         101.        ]
[  0.35980685  28.  

[  0.57162284  28.         337.        ]
[  0.57170235  28.         338.        ]
[  0.57167258  28.         339.        ]
[  0.57202884  28.         340.        ]
[  0.57210243  28.         341.        ]
[  0.57208183  28.         342.        ]
[  0.57216852  28.         343.        ]
[  0.57231471  28.         344.        ]
[  0.57230504  28.         345.        ]
[  0.57234613  28.         346.        ]
[  0.57223256  28.         347.        ]
[  0.57217523  28.         348.        ]
[  0.57198056  28.         349.        ]
[  0.57190215  28.         350.        ]
[  0.57205231  28.         351.        ]
[  0.57198997  28.         352.        ]
[  0.57221311  28.         353.        ]
[  0.57236774  28.         354.        ]
[  0.57229011  28.         355.        ]
[  0.5722882  28.        356.       ]
[  0.57247373  28.         357.        ]
[  0.57242679  28.         358.        ]
[  0.57210001  28.         359.        ]
[  0.57168205  28.         360.        ]
[  0.57110737  28. 

[ 0.07723883 29.         17.        ]
[ 0.09848493 29.         18.        ]
[ 0.11460951 29.         19.        ]
[ 0.13808506 29.         20.        ]
[ 0.16190301 29.         21.        ]
[ 0.17703414 29.         22.        ]
[ 0.17784032 29.         23.        ]
[ 0.19123494 29.         24.        ]
[ 0.19784953 29.         25.        ]
[ 0.18041943 29.         26.        ]
[ 0.1722138 29.        27.       ]
[ 0.16597199 29.         28.        ]
[ 0. 29. 29.]
[ 0.13772405 29.         30.        ]
[ 0.1147162 29.        31.       ]
[ 0.1032028 29.        32.       ]
[ 0.09824741 29.         33.        ]
[ 0.10053798 29.         34.        ]
[ 0.09655851 29.         35.        ]
[ 0.10857518 29.         36.        ]
[ 0.11053436 29.         37.        ]
[ 0.10810655 29.         38.        ]
[ 0.1105391 29.        39.       ]
[ 0.11521666 29.         40.        ]
[ 0.11785065 29.         41.        ]
[ 0.11821748 29.         42.        ]
[ 0.11883899 29.         43.        ]
[ 0.118025

[  0.56038344  29.         288.        ]
[  0.56052912  29.         289.        ]
[  0.56074135  29.         290.        ]
[  0.56077771  29.         291.        ]
[  0.56092075  29.         292.        ]
[  0.56106936  29.         293.        ]
[  0.56131557  29.         294.        ]
[  0.56156494  29.         295.        ]
[  0.56188648  29.         296.        ]
[  0.56208377  29.         297.        ]
[  0.56228802  29.         298.        ]
[  0.56261476  29.         299.        ]
[  0.56283873  29.         300.        ]
[  0.56307853  29.         301.        ]
[  0.56324408  29.         302.        ]
[  0.56347389  29.         303.        ]
[  0.56378453  29.         304.        ]
[  0.5640302  29.        305.       ]
[  0.56429433  29.         306.        ]
[  0.56458472  29.         307.        ]
[  0.56492046  29.         308.        ]
[  0.565277  29.       309.      ]
[  0.56563279  29.         310.        ]
[  0.5659228  29.        311.       ]
[  0.56620919  29.         3

[2.29079459e-01 2.90000000e+01 5.48000000e+02]
[1.86547037e-01 2.90000000e+01 5.49000000e+02]
[1.3657474e-01 2.9000000e+01 5.5000000e+02]
[9.13414238e-02 2.90000000e+01 5.51000000e+02]
[5.33370359e-02 2.90000000e+01 5.52000000e+02]
[2.41444805e-02 2.90000000e+01 5.53000000e+02]
[7.19100164e-03 2.90000000e+01 5.54000000e+02]
[1.93497779e-03 2.90000000e+01 5.55000000e+02]
[8.45089018e-04 2.90000000e+01 5.56000000e+02]
[3.72848468e-04 2.90000000e+01 5.57000000e+02]
[6.95116695e-04 2.90000000e+01 5.58000000e+02]
[1.28706058e-03 2.90000000e+01 5.59000000e+02]
[1.99461349e-03 2.90000000e+01 5.60000000e+02]
[4.12273136e-03 2.90000000e+01 5.61000000e+02]
[4.47085772e-03 2.90000000e+01 5.62000000e+02]
[4.10796698e-03 2.90000000e+01 5.63000000e+02]
[5.36384574e-03 2.90000000e+01 5.64000000e+02]
[1.29977193e-02 2.90000000e+01 5.65000000e+02]
[2.39978204e-02 2.90000000e+01 5.66000000e+02]
[3.69903282e-02 2.90000000e+01 5.67000000e+02]
[4.84700158e-02 2.90000000e+01 5.68000000e+02]
[6.44952927e-02 

[  0.49311245  30.         219.        ]
[  0.50282846  30.         220.        ]
[  0.51102419  30.         221.        ]
[  0.51805357  30.         222.        ]
[  0.52393482  30.         223.        ]
[  0.52885917  30.         224.        ]
[  0.53280634  30.         225.        ]
[  0.53604739  30.         226.        ]
[  0.53878887  30.         227.        ]
[  0.54130852  30.         228.        ]
[  0.5436352  30.        229.       ]
[  0.54579978  30.         230.        ]
[  0.54765417  30.         231.        ]
[  0.54887087  30.         232.        ]
[  0.54971349  30.         233.        ]
[  0.55027549  30.         234.        ]
[  0.5507782  30.        235.       ]
[  0.55107803  30.         236.        ]
[  0.55124042  30.         237.        ]
[  0.55131591  30.         238.        ]
[  0.5512661  30.        239.       ]
[  0.55116524  30.         240.        ]
[  0.55090175  30.         241.        ]
[  0.55059619  30.         242.        ]
[  0.55026265  30.       

[4.24231752e-01 3.00000000e+01 4.92000000e+02]
[4.26981509e-01 3.00000000e+01 4.93000000e+02]
[4.27802124e-01 3.00000000e+01 4.94000000e+02]
[4.27776879e-01 3.00000000e+01 4.95000000e+02]
[4.28870035e-01 3.00000000e+01 4.96000000e+02]
[4.31013042e-01 3.00000000e+01 4.97000000e+02]
[4.29798892e-01 3.00000000e+01 4.98000000e+02]
[4.29162914e-01 3.00000000e+01 4.99000000e+02]
[4.26442688e-01 3.00000000e+01 5.00000000e+02]
[4.22820177e-01 3.00000000e+01 5.01000000e+02]
[4.16570449e-01 3.00000000e+01 5.02000000e+02]
[4.11745967e-01 3.00000000e+01 5.03000000e+02]
[4.07448433e-01 3.00000000e+01 5.04000000e+02]
[4.03026397e-01 3.00000000e+01 5.05000000e+02]
[3.9873717e-01 3.0000000e+01 5.0600000e+02]
[3.94571025e-01 3.00000000e+01 5.07000000e+02]
[3.85761962e-01 3.00000000e+01 5.08000000e+02]
[3.74927e-01 3.00000e+01 5.09000e+02]
[3.60123808e-01 3.00000000e+01 5.10000000e+02]
[3.4248293e-01 3.0000000e+01 5.1100000e+02]
[3.15828843e-01 3.00000000e+01 5.12000000e+02]
[2.90809224e-01 3.00000000e+

[6.9845591e-03 3.1000000e+01 1.6400000e+02]
[8.57646958e-03 3.10000000e+01 1.65000000e+02]
[1.04582294e-02 3.10000000e+01 1.66000000e+02]
[1.27363968e-02 3.10000000e+01 1.67000000e+02]
[1.53197876e-02 3.10000000e+01 1.68000000e+02]
[1.845152e-02 3.100000e+01 1.690000e+02]
[2.16553596e-02 3.10000000e+01 1.70000000e+02]
[2.48654175e-02 3.10000000e+01 1.71000000e+02]
[2.79087009e-02 3.10000000e+01 1.72000000e+02]
[3.08603183e-02 3.10000000e+01 1.73000000e+02]
[3.36933379e-02 3.10000000e+01 1.74000000e+02]
[3.64576504e-02 3.10000000e+01 1.75000000e+02]
[3.92982515e-02 3.10000000e+01 1.76000000e+02]
[4.20971114e-02 3.10000000e+01 1.77000000e+02]
[4.49790417e-02 3.10000000e+01 1.78000000e+02]
[4.8018076e-02 3.1000000e+01 1.7900000e+02]
[5.10878041e-02 3.10000000e+01 1.80000000e+02]
[5.43103673e-02 3.10000000e+01 1.81000000e+02]
[5.75503263e-02 3.10000000e+01 1.82000000e+02]
[6.09282113e-02 3.10000000e+01 1.83000000e+02]
[6.38199351e-02 3.10000000e+01 1.84000000e+02]
[6.66939707e-02 3.1000000

[  0.57645262  31.         423.        ]
[  0.57471904  31.         424.        ]
[  0.57315102  31.         425.        ]
[  0.57263548  31.         426.        ]
[  0.57289735  31.         427.        ]
[  0.57440867  31.         428.        ]
[  0.57520383  31.         429.        ]
[  0.57590881  31.         430.        ]
[  0.57583826  31.         431.        ]
[  0.57590998  31.         432.        ]
[  0.57664219  31.         433.        ]
[  0.57715801  31.         434.        ]
[  0.57731543  31.         435.        ]
[  0.57754308  31.         436.        ]
[  0.57719349  31.         437.        ]
[  0.57730092  31.         438.        ]
[  0.57688733  31.         439.        ]
[  0.57593656  31.         440.        ]
[  0.5727572  31.        441.       ]
[  0.57400916  31.         442.        ]
[  0.57246659  31.         443.        ]
[  0.58005494  31.         444.        ]
[  0.5888177  31.        445.       ]
[  0.60017435  31.         446.        ]
[  0.62095602  31.    

[ 0.35547288 32.         87.        ]
[ 0.36983876 32.         88.        ]
[ 0.38139668 32.         89.        ]
[ 0.39030033 32.         90.        ]
[ 0.39698774 32.         91.        ]
[ 0.40170222 32.         92.        ]
[ 0.4047044 32.        93.       ]
[ 0.40605092 32.         94.        ]
[ 0.40562909 32.         95.        ]
[ 0.40401658 32.         96.        ]
[ 0.40180526 32.         97.        ]
[ 0.39881747 32.         98.        ]
[ 0.39567877 32.         99.        ]
[  0.39188111  32.         100.        ]
[  0.3880047  32.        101.       ]
[  0.38458292  32.         102.        ]
[  0.38097997  32.         103.        ]
[  0.37795027  32.         104.        ]
[  0.37476574  32.         105.        ]
[  0.37165743  32.         106.        ]
[  0.36802694  32.         107.        ]
[  0.36420538  32.         108.        ]
[  0.35926341  32.         109.        ]
[  0.3534326  32.        110.       ]
[  0.3465281  32.        111.       ]
[  0.33841027  32.        

[  0.57063476  32.         338.        ]
[  0.57059724  32.         339.        ]
[  0.57094436  32.         340.        ]
[  0.57101199  32.         341.        ]
[  0.57098651  32.         342.        ]
[  0.57106893  32.         343.        ]
[  0.57120688  32.         344.        ]
[  0.57119535  32.         345.        ]
[  0.5712271  32.        346.       ]
[  0.57110443  32.         347.        ]
[  0.5710363  32.        348.       ]
[  0.57082863  32.         349.        ]
[  0.57074323  32.         350.        ]
[  0.57088751  32.         351.        ]
[  0.57082835  32.         352.        ]
[  0.57105873  32.         353.        ]
[  0.57122127  32.         354.        ]
[  0.57115406  32.         355.        ]
[  0.57116646  32.         356.        ]
[  0.57135049  32.         357.        ]
[  0.57128953  32.         358.        ]
[  0.57094316  32.         359.        ]
[  0.57049552  32.         360.        ]
[  0.56989247  32.         361.        ]
[  0.56930103  32.    

[1.37368495e-01 3.20000000e+01 5.75000000e+02]
[1.36525543e-01 3.20000000e+01 5.76000000e+02]
[1.40656341e-01 3.20000000e+01 5.77000000e+02]
[1.45204689e-01 3.20000000e+01 5.78000000e+02]
[1.50168712e-01 3.20000000e+01 5.79000000e+02]
[1.55491638e-01 3.20000000e+01 5.80000000e+02]
[1.6108797e-01 3.2000000e+01 5.8100000e+02]
[1.66887385e-01 3.20000000e+01 5.82000000e+02]
[1.72917276e-01 3.20000000e+01 5.83000000e+02]
[ 0.08358971 33.          0.        ]
[ 0.07763012 33.          1.        ]
[ 0.07199898 33.          2.        ]
[ 0.06682296 33.          3.        ]
[ 0.06218708 33.          4.        ]
[ 0.0581417 33.         5.       ]
[ 0.05471098 33.          6.        ]
[ 0.05190089 33.          7.        ]
[ 0.04915171 33.          8.        ]
[ 0.04817259 33.          9.        ]
[ 0.04767769 33.         10.        ]
[ 0.0464528 33.        11.       ]
[ 0.04475661 33.         12.        ]
[ 0.04661311 33.         13.        ]
[ 0.05500544 33.         14.        ]
[ 0.06324003 33.

[  0.55102531  33.         238.        ]
[  0.55092251  33.         239.        ]
[  0.55077368  33.         240.        ]
[  0.55047101  33.         241.        ]
[  0.55013267  33.         242.        ]
[  0.54976325  33.         243.        ]
[  0.54984332  33.         244.        ]
[  0.55025691  33.         245.        ]
[  0.55095329  33.         246.        ]
[  0.5518097  33.        247.       ]
[  0.55238265  33.         248.        ]
[  0.55286759  33.         249.        ]
[  0.55307895  33.         250.        ]
[  0.55312718  33.         251.        ]
[  0.55301242  33.         252.        ]
[  0.55266219  33.         253.        ]
[  0.55209905  33.         254.        ]
[  0.5513414  33.        255.       ]
[  0.550591  33.       256.      ]
[  0.55004233  33.         257.        ]
[  0.55008828  33.         258.        ]
[  0.5504497  33.        259.       ]
[  0.55097057  33.         260.        ]
[  0.55147212  33.         261.        ]
[  0.55181111  33.         262.

[4.16548465e-01 3.30000000e+01 4.84000000e+02]
[4.19522006e-01 3.30000000e+01 4.85000000e+02]
[4.24564531e-01 3.30000000e+01 4.86000000e+02]
[4.26716818e-01 3.30000000e+01 4.87000000e+02]
[4.26989737e-01 3.30000000e+01 4.88000000e+02]
[4.27491377e-01 3.30000000e+01 4.89000000e+02]
[4.28797211e-01 3.30000000e+01 4.90000000e+02]
[4.31057585e-01 3.30000000e+01 4.91000000e+02]
[4.33443374e-01 3.30000000e+01 4.92000000e+02]
[4.36005922e-01 3.30000000e+01 4.93000000e+02]
[4.36831199e-01 3.30000000e+01 4.94000000e+02]
[4.36741822e-01 3.30000000e+01 4.95000000e+02]
[4.37881227e-01 3.30000000e+01 4.96000000e+02]
[4.39995763e-01 3.30000000e+01 4.97000000e+02]
[4.38886961e-01 3.30000000e+01 4.98000000e+02]
[4.38436271e-01 3.30000000e+01 4.99000000e+02]
[4.3593175e-01 3.3000000e+01 5.0000000e+02]
[4.32594393e-01 3.30000000e+01 5.01000000e+02]
[4.26752884e-01 3.30000000e+01 5.02000000e+02]
[4.22267361e-01 3.30000000e+01 5.03000000e+02]
[4.1821757e-01 3.3000000e+01 5.0400000e+02]
[4.14144463e-01 3.3

[1.98042917e-02 3.40000000e+01 1.43000000e+02]
[1.64560382e-02 3.40000000e+01 1.44000000e+02]
[1.30790719e-02 3.40000000e+01 1.45000000e+02]
[9.9343617e-03 3.4000000e+01 1.4600000e+02]
[7.06332914e-03 3.40000000e+01 1.47000000e+02]
[4.69712743e-03 3.40000000e+01 1.48000000e+02]
[2.85862163e-03 3.40000000e+01 1.49000000e+02]
[1.46070015e-03 3.40000000e+01 1.50000000e+02]
[5.56842287e-04 3.40000000e+01 1.51000000e+02]
[1.026177e-04 3.400000e+01 1.520000e+02]
[3.36663902e-06 3.40000000e+01 1.53000000e+02]
[1.39247709e-04 3.40000000e+01 1.54000000e+02]
[4.07258776e-04 3.40000000e+01 1.55000000e+02]
[7.43790376e-04 3.40000000e+01 1.56000000e+02]
[1.07064458e-03 3.40000000e+01 1.57000000e+02]
[1.38433471e-03 3.40000000e+01 1.58000000e+02]
[1.7521455e-03 3.4000000e+01 1.5900000e+02]
[2.16815865e-03 3.40000000e+01 1.60000000e+02]
[2.69729368e-03 3.40000000e+01 1.61000000e+02]
[3.34999077e-03 3.40000000e+01 1.62000000e+02]
[4.19025852e-03 3.40000000e+01 1.63000000e+02]
[5.30426935e-03 3.4000000

[  0.57371188  34.         389.        ]
[  0.57428321  34.         390.        ]
[  0.57424668  34.         391.        ]
[  0.57411036  34.         392.        ]
[  0.57404658  34.         393.        ]
[  0.57399675  34.         394.        ]
[  0.57478968  34.         395.        ]
[  0.57499841  34.         396.        ]
[  0.5759423  34.        397.       ]
[  0.57636253  34.         398.        ]
[  0.5767947  34.        399.       ]
[  0.57848454  34.         400.        ]
[  0.579712  34.       401.      ]
[  0.58083679  34.         402.        ]
[  0.58139613  34.         403.        ]
[  0.58182114  34.         404.        ]
[  0.58159512  34.         405.        ]
[  0.58172475  34.         406.        ]
[  0.58122599  34.         407.        ]
[  0.58119992  34.         408.        ]
[  0.58077284  34.         409.        ]
[  0.5801118  34.        410.       ]
[  0.57987545  34.         411.        ]
[  0.57999253  34.         412.        ]
[  0.58058152  34.         413.

[ 0.10019149 35.         46.        ]
[ 0.09969416 35.         47.        ]
[ 0.10077295 35.         48.        ]
[ 0.09745148 35.         49.        ]
[ 0.10074278 35.         50.        ]
[ 0.10227206 35.         51.        ]
[ 0.10583666 35.         52.        ]
[ 0.10953803 35.         53.        ]
[ 0.11118575 35.         54.        ]
[ 0.11469205 35.         55.        ]
[ 0.11402697 35.         56.        ]
[ 0.11321286 35.         57.        ]
[ 0.10919958 35.         58.        ]
[ 0.10523428 35.         59.        ]
[ 0.10118668 35.         60.        ]
[ 0.09750053 35.         61.        ]
[ 0.08895078 35.         62.        ]
[ 0.08080501 35.         63.        ]
[ 0.07392369 35.         64.        ]
[ 0.06522315 35.         65.        ]
[5.59598514e-02 3.50000000e+01 6.60000000e+01]
[4.58165866e-02 3.50000000e+01 6.70000000e+01]
[3.63649171e-02 3.50000000e+01 6.80000000e+01]
[2.72474701e-02 3.50000000e+01 6.90000000e+01]
[1.72567434e-02 3.50000000e+01 7.00000000e+01]
[9.08

[  0.55889817  35.         286.        ]
[  0.55916909  35.         287.        ]
[  0.55931492  35.         288.        ]
[  0.5594633  35.        289.       ]
[  0.55967611  35.         290.        ]
[  0.55971449  35.         291.        ]
[  0.55985658  35.         292.        ]
[  0.55999925  35.         293.        ]
[  0.56024221  35.         294.        ]
[  0.56048927  35.         295.        ]
[  0.56080623  35.         296.        ]
[  0.56100407  35.         297.        ]
[  0.5612092  35.        298.       ]
[  0.56153471  35.         299.        ]
[  0.56176436  35.         300.        ]
[  0.5620152  35.        301.       ]
[  0.5621888  35.        302.       ]
[  0.56242415  35.         303.        ]
[  0.56273532  35.         304.        ]
[  0.56298295  35.         305.        ]
[  0.56324353  35.         306.        ]
[  0.56353432  35.         307.        ]
[  0.56387505  35.         308.        ]
[  0.56423272  35.         309.        ]
[  0.56458338  35.         3

[1.39283518e-01 3.50000000e+01 5.19000000e+02]
[1.19896465e-01 3.50000000e+01 5.20000000e+02]
[1.01321283e-01 3.50000000e+01 5.21000000e+02]
[8.42907056e-02 3.50000000e+01 5.22000000e+02]
[6.86541488e-02 3.50000000e+01 5.23000000e+02]
[5.43289403e-02 3.50000000e+01 5.24000000e+02]
[4.10154592e-02 3.50000000e+01 5.25000000e+02]
[3.01439109e-02 3.50000000e+01 5.26000000e+02]
[2.08188029e-02 3.50000000e+01 5.27000000e+02]
[1.26017297e-02 3.50000000e+01 5.28000000e+02]
[5.64939178e-03 3.50000000e+01 5.29000000e+02]
[9.32428015e-04 3.50000000e+01 5.30000000e+02]
[5.75988769e-04 3.50000000e+01 5.31000000e+02]
[8.42058996e-03 3.50000000e+01 5.32000000e+02]
[2.66389536e-02 3.50000000e+01 5.33000000e+02]
[6.04203123e-02 3.50000000e+01 5.34000000e+02]
[1.07677808e-01 3.50000000e+01 5.35000000e+02]
[1.57407276e-01 3.50000000e+01 5.36000000e+02]
[2.10629101e-01 3.50000000e+01 5.37000000e+02]
[2.59467129e-01 3.50000000e+01 5.38000000e+02]
[2.94371908e-01 3.50000000e+01 5.39000000e+02]
[3.04172011e-

[5.88734127e-04 3.60000000e+01 1.57000000e+02]
[8.33765237e-04 3.60000000e+01 1.58000000e+02]
[1.13250105e-03 3.60000000e+01 1.59000000e+02]
[1.48142969e-03 3.60000000e+01 1.60000000e+02]
[1.93675291e-03 3.60000000e+01 1.61000000e+02]
[2.51196645e-03 3.60000000e+01 1.62000000e+02]
[3.26748957e-03 3.60000000e+01 1.63000000e+02]
[4.28731794e-03 3.60000000e+01 1.64000000e+02]
[5.6432244e-03 3.6000000e+01 1.6500000e+02]
[7.29708305e-03 3.60000000e+01 1.66000000e+02]
[9.3503859e-03 3.6000000e+01 1.6700000e+02]
[1.17309801e-02 3.60000000e+01 1.68000000e+02]
[1.4667675e-02 3.6000000e+01 1.6900000e+02]
[1.77205848e-02 3.60000000e+01 1.70000000e+02]
[2.081777e-02 3.600000e+01 1.710000e+02]
[2.37846013e-02 3.60000000e+01 1.72000000e+02]
[2.6681329e-02 3.6000000e+01 1.7300000e+02]
[2.94802639e-02 3.60000000e+01 1.74000000e+02]
[3.22255153e-02 3.60000000e+01 1.75000000e+02]
[3.50615245e-02 3.60000000e+01 1.76000000e+02]
[3.7868703e-02 3.6000000e+01 1.7700000e+02]
[4.07725175e-02 3.60000000e+01 1.7

In [ ]:
coeff

In [ ]:
# NDVIn = np.empty([1,60])
# for i in enumerate(subplots):
#     for j in subplots:
#         temp = [(i-j)/(i+j)]
#         temp = np.array(temp).reshape(1, -1)
# #         coeff = linregress(temp, lai)
# #         coeff = coeff.rvalue**2
#         NDVIn = np.vstack([NDVIn, temp])
    

In [ ]:
NDVIn

In [ ]:
top_bands = np.where(NDVIn == NDVIn[0].max())
top_bands